plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.78'
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = 'https://maven.createmod.net' }
    maven { url = 'https://mvn.devos.one/snapshots' }
    maven { url = 'https://maven.blamejared.com/' }
}

base { archivesName = mod_id }
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            jvmArguments.addAll '-Xmx8G', '-Xms2G'
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            jvmArguments.addAll '-Xmx4G', '-Xms1G'
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').absolutePath, '--existing', file('src/main/resources/').absolutePath
        }
    }
    mods { "${mod_id}" { sourceSet(sourceSets.main) } }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [minecraft_version:minecraft_version, minecraft_version_range:minecraft_version_range,
        neo_version:neo_version, neo_version_range:neo_version_range, loader_version_range:loader_version_range,
        mod_id:mod_id, mod_name:mod_name, mod_license:mod_license, mod_version:mod_version,
        mod_authors:mod_authors, mod_description:mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

processResources { duplicatesStrategy = DuplicatesStrategy.WARN }
idea { module { downloadSources = true; downloadJavadoc = true } }
