org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
neo_version_range=[21.1.219,21.2)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

mod_id=livingrealms
mod_name=Living Realms
mod_license=MIT
mod_version=3.0.0-rc4
mod_group_id=dev.livingrealms
mod_authors=Romy
mod_description=Persistent civilization and ecosystem simulation for Minecraft, integrated with Create.
