package dev.livingrealms.sim.persistence.codec;

import dev.livingrealms.sim.aviation.*;
import dev.livingrealms.sim.config.SimulationConfig;
import dev.livingrealms.sim.civilization.*;
import dev.livingrealms.sim.civilian.AppearanceProfile;
import dev.livingrealms.sim.civilian.CitizenRole;
import dev.livingrealms.sim.construction.ConstructionPhase;
import dev.livingrealms.sim.construction.RegisteredPlayerStructure;
import dev.livingrealms.sim.diplomacy.*;
import dev.livingrealms.sim.ecology.*;
import dev.livingrealms.sim.faction.*;
import dev.livingrealms.sim.government.*;
import dev.livingrealms.sim.industry.*;
import dev.livingrealms.sim.law.*;
import dev.livingrealms.sim.logistics.*;
import dev.livingrealms.sim.military.*;
import dev.livingrealms.sim.naval.*;
import dev.livingrealms.sim.player.*;
import dev.livingrealms.sim.social.*;
import dev.livingrealms.sim.transport.*;
import dev.livingrealms.sim.underworld.StolenGoodsEntry;
import dev.livingrealms.sim.underworld.StolenGoodsLedger;
import dev.livingrealms.sim.underworld.UnderworldContract;
import dev.livingrealms.sim.underworld.UnderworldContractType;
import dev.livingrealms.sim.underworld.UnderworldProfile;
import dev.livingrealms.sim.world.*;
import java.io.*;
import java.util.*;


/** Social citizens, civilization profiles, humanity and pirate-hideout persistence. */
public final class SocietyCodec {
    private SocietyCodec() {}

public static void writeV11Social(DataOutputStream out,SimulationState state)throws IOException{
        out.writeInt(state.socialCitizens().size());
        for(SocialCitizen c:state.socialCitizens()){
            out.writeLong(c.id());out.writeLong(c.factionId());out.writeLong(c.settlementId());out.writeInt(c.projectionSlot());CodecIO.writeString(out,c.name());out.writeInt(c.skinVariant());out.writeInt(c.role().ordinal());out.writeLong(c.birthDay());out.writeDouble(c.health());out.writeDouble(c.money());out.writeBoolean(c.alive());
            CitizenNeeds n=c.needs();out.writeDouble(n.hunger());out.writeDouble(n.safety());out.writeDouble(n.social());out.writeDouble(n.status());out.writeDouble(n.comfort());
            CitizenPersonality p=c.personality();out.writeDouble(p.aggression());out.writeDouble(p.tradeAffinity());out.writeDouble(p.caution());out.writeDouble(p.greed());out.writeDouble(p.loyalty());out.writeDouble(p.treachery());
            List<CitizenMemory> memories=c.memories();out.writeInt(memories.size());for(CitizenMemory m:memories){out.writeLong(m.day());out.writeInt(m.type().ordinal());CodecIO.writeString(out,m.subjectKey());CodecIO.writeString(out,m.sourceKey());CodecIO.writeString(out,m.summary());CodecIO.writePosition(out,m.position());out.writeDouble(m.importance());out.writeDouble(m.confidence());}
            var relationships=new ArrayList<>(c.relationships().values());relationships.sort(Comparator.comparing(CitizenRelationship::targetKey));out.writeInt(relationships.size());for(CitizenRelationship r:relationships){CodecIO.writeString(out,r.targetKey());out.writeDouble(r.friendship());out.writeDouble(r.hostility());out.writeDouble(r.romance());out.writeDouble(r.rivalry());out.writeDouble(r.trust());out.writeInt(r.familyBond().ordinal());}
        }
    }

public static void readV11Social(DataInputStream in,SimulationState state)throws IOException{
        int count=CodecIO.checkedCount(in.readInt(),100000,"social citizens");
        for(int i=0;i<count;i++){
            long id=in.readLong(),faction=in.readLong(),settlement=in.readLong();int slot=CodecIO.checkedCount(in.readInt(),100000,"citizen projection slot");String name=CodecIO.readString(in);int skin=CodecIO.checkedCount(in.readInt(),47,"citizen skin");CitizenRole role=CitizenRole.values()[CodecIO.enumOrdinal(in.readInt(),CitizenRole.values().length,"citizen role")];long birthDay=in.readLong();double health=in.readDouble(),money=in.readDouble();boolean alive=in.readBoolean();
            CitizenNeeds needs=new CitizenNeeds();needs.restore(in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble());CitizenPersonality personality=new CitizenPersonality(in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble());
            SocialCitizen citizen=new SocialCitizen(id,faction,settlement,slot,name,skin,role,birthDay,personality);citizen.restoreCore(role,health,money,alive);citizen.needs().restore(needs.hunger(),needs.safety(),needs.social(),needs.status(),needs.comfort());
            int memories=CodecIO.checkedCount(in.readInt(),SocialCitizen.MAX_MEMORIES,"citizen memories");for(int j=0;j<memories;j++){CitizenMemory memory=new CitizenMemory(in.readLong(),MemoryType.values()[CodecIO.enumOrdinal(in.readInt(),MemoryType.values().length,"memory type")],CodecIO.readString(in),CodecIO.readString(in),CodecIO.readString(in),CodecIO.readPosition(in),in.readDouble(),in.readDouble());citizen.restoreMemory(memory);}
            int relationships=CodecIO.checkedCount(in.readInt(),SocialCitizen.MAX_RELATIONSHIPS,"citizen relationships");for(int j=0;j<relationships;j++){CitizenRelationship rel=new CitizenRelationship(CodecIO.readString(in));rel.restore(in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),FamilyBond.values()[CodecIO.enumOrdinal(in.readInt(),FamilyBond.values().length,"family bond")]);citizen.restoreRelationship(rel);}
            state.addSocialCitizen(citizen);
        }
    }

public static void writeV12Civilization(DataOutputStream out,SimulationState state)throws IOException{
        var settlements=new ArrayList<>(state.settlementCivilizations().values());settlements.sort(Comparator.comparingLong(SettlementCivilizationState::settlementId));out.writeInt(settlements.size());
        for(SettlementCivilizationState c:settlements){out.writeLong(c.settlementId());out.writeLong(c.heritageFactionId());out.writeDouble(c.sanitation());out.writeDouble(c.diseasePressure());out.writeDouble(c.education());out.writeDouble(c.waterSecurity());out.writeDouble(c.refugeePressure());out.writeDouble(c.banditPressure());out.writeDouble(c.culturalCohesion());out.writeDouble(c.assimilation());out.writeDouble(c.resourcePressure());out.writeLong(c.lastEpidemicDay());out.writeLong(c.lastMigrationDay());}
        var factions=new ArrayList<>(state.factionCivilizations().values());factions.sort(Comparator.comparingLong(FactionCivilizationState::factionId));out.writeInt(factions.size());
        for(FactionCivilizationState c:factions){out.writeLong(c.factionId());CodecIO.writeString(out,c.cultureName());CodecIO.writeString(out,c.faithName());CodecIO.writeString(out,c.dialectName());out.writeDouble(c.culturalInfluence());out.writeDouble(c.religiousInfluence());out.writeDouble(c.education());out.writeDouble(c.propaganda());out.writeDouble(c.intelligence());out.writeLong(c.tributaryToFactionId());out.writeDouble(c.tributeRate());var spies=new ArrayList<>(c.spyNetworks().entrySet());spies.sort(Map.Entry.comparingByKey());out.writeInt(spies.size());for(var e:spies){out.writeLong(e.getKey());out.writeDouble(e.getValue());}}
        out.writeInt(state.resourceClaims().size());for(ResourceClaim c:state.resourceClaims()){out.writeLong(c.id());out.writeLong(c.factionId());out.writeLong(c.settlementId());out.writeInt(c.type().ordinal());CodecIO.writePosition(out,c.position());out.writeDouble(c.strength());out.writeLong(c.contestedByFactionId());out.writeBoolean(c.active());}
        out.writeInt(state.raids().size());for(RaidParty r:state.raids()){out.writeLong(r.id());out.writeLong(r.attackerFactionId());out.writeLong(r.originSettlementId());out.writeLong(r.targetSettlementId());out.writeLong(r.createdDay());out.writeInt(r.manpower());out.writeDouble(r.morale());out.writeDouble(r.progress());out.writeBoolean(r.active());out.writeBoolean(r.bandit());}
        out.writeInt(state.legends().size());for(LegendRecord l:state.legends()){out.writeLong(l.id());out.writeLong(l.day());out.writeLong(l.factionId());out.writeLong(l.settlementId());CodecIO.writeString(out,l.subjectKey());CodecIO.writeString(out,l.title());CodecIO.writeString(out,l.description());out.writeDouble(l.renown());out.writeBoolean(l.monumented());}
    }

public static void readV12Civilization(DataInputStream in,SimulationState state)throws IOException{
        int n=CodecIO.checkedCount(in.readInt(),100000,"settlement civilization profiles");for(int i=0;i<n;i++){SettlementCivilizationState c=new SettlementCivilizationState(in.readLong(),in.readLong());c.restore(c.heritageFactionId(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readLong(),in.readLong());state.restoreSettlementCivilization(c);}
        n=CodecIO.checkedCount(in.readInt(),10000,"faction civilization profiles");for(int i=0;i<n;i++){long factionId=in.readLong();FactionCivilizationState c=new FactionCivilizationState(factionId,CodecIO.readString(in),CodecIO.readString(in),CodecIO.readString(in));double culture=in.readDouble(),religion=in.readDouble(),education=in.readDouble(),propaganda=in.readDouble(),intelligence=in.readDouble();long overlord=in.readLong();double tribute=in.readDouble();int sc=CodecIO.checkedCount(in.readInt(),FactionCivilizationState.MAX_SPY_NETWORKS,"spy networks");Map<Long,Double> spies=new LinkedHashMap<>();for(int j=0;j<sc;j++)spies.put(in.readLong(),in.readDouble());try{c.restore(culture,religion,education,propaganda,intelligence,overlord,tribute,spies);}catch(IllegalArgumentException bad){throw new IOException("invalid faction civilization profile",bad);}state.restoreFactionCivilization(c);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_RESOURCE_CLAIMS,"resource claims");for(int i=0;i<n;i++){ResourceClaim c=new ResourceClaim(in.readLong(),in.readLong(),in.readLong(),ResourceClaimType.values()[CodecIO.enumOrdinal(in.readInt(),ResourceClaimType.values().length,"resource claim type")],CodecIO.readPosition(in),in.readDouble());c.restore(c.strength(),in.readLong(),in.readBoolean());state.addResourceClaim(c);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_RAIDS,"raids");for(int i=0;i<n;i++){long id=in.readLong(),attacker=in.readLong(),origin=in.readLong(),target=in.readLong(),created=in.readLong();int manpower=CodecIO.checkedCount(in.readInt(),100000,"raid manpower");double morale=in.readDouble(),progress=in.readDouble();boolean active=in.readBoolean(),bandit=in.readBoolean();RaidParty r=new RaidParty(id,attacker,origin,target,created,Math.max(1,manpower),morale,bandit);r.restore(manpower,morale,progress,active);state.addRaid(r);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_LEGENDS,"legends");for(int i=0;i<n;i++){LegendRecord l=new LegendRecord(in.readLong(),in.readLong(),in.readLong(),in.readLong(),CodecIO.readString(in),CodecIO.readString(in),CodecIO.readString(in),in.readDouble());boolean monumented=in.readBoolean();if(monumented)l.markMonumented();state.addLegend(l);}
    }

public static void writeV13Humanity(DataOutputStream out,SimulationState state)throws IOException{
        var citizens=new ArrayList<>(state.socialCitizens());citizens.sort(Comparator.comparingLong(SocialCitizen::id));out.writeInt(citizens.size());for(SocialCitizen c:citizens){out.writeLong(c.id());out.writeLong(c.householdId());out.writeDouble(c.professionSkill());}
        var settlements=new ArrayList<>(state.settlementCivilizations().values());settlements.sort(Comparator.comparingLong(SettlementCivilizationState::settlementId));out.writeInt(settlements.size());for(SettlementCivilizationState c:settlements){out.writeLong(c.settlementId());out.writeDouble(c.quarantineStrength());for(KnowledgeDomain d:KnowledgeDomain.values())out.writeDouble(c.knowledge(d));}
        var factions=new ArrayList<>(state.factionCivilizations().values());factions.sort(Comparator.comparingLong(FactionCivilizationState::factionId));out.writeInt(factions.size());for(FactionCivilizationState c:factions){out.writeLong(c.factionId());out.writeDouble(c.mercantileTradition());out.writeDouble(c.martialTradition());out.writeDouble(c.agrarianTradition());out.writeDouble(c.artisticTradition());out.writeDouble(c.religiousTolerance());out.writeDouble(c.openness());out.writeDouble(c.lawSeverity());out.writeDouble(c.dueProcess());out.writeDouble(c.refugeeAcceptance());}
        var households=new ArrayList<>(state.households());households.sort(Comparator.comparingLong(HouseholdState::id));out.writeInt(households.size());for(HouseholdState h:households){out.writeLong(h.id());out.writeLong(h.factionId());out.writeLong(h.settlementId());out.writeLong(h.foundedDay());out.writeBoolean(h.active());out.writeDouble(h.sharedWealth());CodecIO.writeString(out,h.homeKey());out.writeInt(h.memberIds().size());for(long id:h.memberIds())out.writeLong(id);out.writeInt(h.children().size());for(DependentChild child:h.children()){out.writeLong(child.id());out.writeLong(child.birthDay());out.writeLong(child.parentAId());out.writeLong(child.parentBId());out.writeLong(child.adoptiveParentAId());out.writeLong(child.adoptiveParentBId());}}
        var epidemics=new ArrayList<>(state.epidemics());epidemics.sort(Comparator.comparingLong(EpidemicRecord::id));out.writeInt(epidemics.size());for(EpidemicRecord e:epidemics){out.writeLong(e.id());out.writeLong(e.settlementId());out.writeLong(e.startDay());CodecIO.writeString(out,e.diseaseKey());out.writeDouble(e.severity());out.writeDouble(e.infectedFraction());out.writeInt(e.cumulativeDeaths());out.writeLong(e.lastUpdateDay());out.writeBoolean(e.active());}
        var migrations=new ArrayList<>(state.migrationGroups());migrations.sort(Comparator.comparingLong(MigrationGroup::id));out.writeInt(migrations.size());for(MigrationGroup g:migrations){out.writeLong(g.id());out.writeLong(g.originFactionId());out.writeLong(g.sourceSettlementId());out.writeLong(g.targetSettlementId());out.writeLong(g.campSettlementId());out.writeLong(g.createdDay());out.writeInt(g.people());out.writeInt(g.reason().ordinal());out.writeInt(g.status().ordinal());out.writeDouble(g.progress());out.writeDouble(g.food());out.writeDouble(g.health());out.writeInt(g.householdIds().size());for(long h:g.householdIds())out.writeLong(h);}
        var justice=new ArrayList<>(state.justiceCases());justice.sort(Comparator.comparingLong(JusticeCase::id));out.writeInt(justice.size());for(JusticeCase j:justice){out.writeLong(j.id());out.writeLong(j.factionId());out.writeLong(j.settlementId());out.writeLong(j.openedDay());CodecIO.writeString(out,j.accusedKey());out.writeInt(j.crimeType().ordinal());out.writeInt(j.status().ordinal());out.writeInt(j.sentence().ordinal());out.writeDouble(j.fine());out.writeLong(j.releaseDay());}
        var caches=new ArrayList<>(state.hiddenCaches());caches.sort(Comparator.comparingLong(HiddenCache::id));out.writeInt(caches.size());for(HiddenCache c:caches){out.writeLong(c.id());out.writeLong(c.factionId());out.writeLong(c.settlementId());out.writeLong(c.createdDay());CodecIO.writePosition(out,c.position());for(ResourceType r:ResourceType.values())out.writeDouble(c.goods().getOrDefault(r,0.0));out.writeLong(c.discoveredByFactionId());out.writeBoolean(c.recovered());}
        var pirates=new ArrayList<>(state.pirateBands());pirates.sort(Comparator.comparingLong(PirateBand::id));out.writeInt(pirates.size());for(PirateBand b:pirates){out.writeLong(b.id());out.writeLong(b.originSettlementId());out.writeLong(b.createdDay());CodecIO.writePosition(out,b.position());out.writeInt(b.strength());out.writeDouble(b.morale());out.writeDouble(b.loot());out.writeBoolean(b.active());}
        var marriages=new ArrayList<>(state.diplomaticMarriages());marriages.sort(Comparator.comparingLong(DiplomaticMarriage::id));out.writeInt(marriages.size());for(DiplomaticMarriage m:marriages){out.writeLong(m.id());out.writeLong(m.day());out.writeLong(m.citizenA());out.writeLong(m.citizenB());out.writeLong(m.factionA());out.writeLong(m.factionB());out.writeBoolean(m.active());}
        var dynasties=new ArrayList<>(state.dynasties().values());dynasties.sort(Comparator.comparingLong(DynastyState::factionId));out.writeInt(dynasties.size());for(DynastyState d:dynasties){out.writeLong(d.factionId());out.writeLong(d.foundedDay());CodecIO.writeString(out,d.houseName());out.writeLong(d.rulerCitizenId());out.writeLong(d.heirCitizenId());out.writeLong(d.regentCitizenId());out.writeDouble(d.prestige());out.writeBoolean(d.successionCrisis());out.writeLong(d.crisisSinceDay());out.writeInt(d.generation());out.writeLong(d.lastSuccessionDay());}
        var civic=new ArrayList<>(state.civicEvents());civic.sort(Comparator.comparingLong(CivicEvent::id));out.writeInt(civic.size());for(CivicEvent e:civic){out.writeLong(e.id());out.writeLong(e.factionId());out.writeLong(e.settlementId());out.writeLong(e.startDay());out.writeLong(e.endDay());out.writeInt(e.type().ordinal());CodecIO.writeString(out,e.title());out.writeDouble(e.attendance());out.writeDouble(e.intensity());out.writeBoolean(e.active());}
        var intel=new ArrayList<>(state.intelligenceOperations());intel.sort(Comparator.comparingLong(IntelligenceOperation::id));out.writeInt(intel.size());for(IntelligenceOperation o:intel){out.writeLong(o.id());out.writeLong(o.sourceFactionId());out.writeLong(o.targetFactionId());out.writeLong(o.startDay());out.writeLong(o.agentCitizenId());out.writeInt(o.type().ordinal());out.writeDouble(o.progress());out.writeDouble(o.secrecy());out.writeDouble(o.quality());out.writeBoolean(o.discovered());out.writeBoolean(o.active());}
        var propaganda=new ArrayList<>(state.propagandaCampaigns());propaganda.sort(Comparator.comparingLong(PropagandaCampaign::id));out.writeInt(propaganda.size());for(PropagandaCampaign c:propaganda){out.writeLong(c.id());out.writeLong(c.factionId());out.writeLong(c.settlementId());out.writeLong(c.startDay());out.writeLong(c.endDay());out.writeInt(c.theme().ordinal());out.writeDouble(c.intensity());out.writeDouble(c.reach());out.writeBoolean(c.active());}
        var ruins=new ArrayList<>(state.ruinSites());ruins.sort(Comparator.comparingLong(RuinSite::id));out.writeInt(ruins.size());for(RuinSite r:ruins){out.writeLong(r.id());out.writeLong(r.originalSettlementId());out.writeLong(r.originalFactionId());out.writeLong(r.createdDay());CodecIO.writePosition(out,r.position());CodecIO.writeString(out,r.originalName());CodecIO.writeString(out,r.cause());out.writeDouble(r.preservation());out.writeBoolean(r.looted());out.writeBoolean(r.reclaimed());}
        var tasks=new ArrayList<>(state.assistanceTasks());tasks.sort(Comparator.comparingLong(AssistanceTask::id));out.writeInt(tasks.size());for(AssistanceTask t:tasks){out.writeLong(t.id());out.writeLong(t.factionId());out.writeLong(t.settlementId());out.writeLong(t.createdDay());out.writeLong(t.expiresDay());out.writeInt(t.type().ordinal());CodecIO.writeString(out,t.causeKey());out.writeDouble(t.initialPressure());out.writeDouble(t.remainingPressure());out.writeInt(t.status().ordinal());}
    }

public static void readV13Humanity(DataInputStream in,SimulationState state,int version)throws IOException{
        int n=CodecIO.checkedCount(in.readInt(),100000,"citizen humanity links");for(int i=0;i<n;i++){long citizenId=in.readLong(),householdId=in.readLong();double skill=in.readDouble();SocialCitizen c=state.findSocialCitizen(citizenId).orElseThrow(()->new IOException("unknown citizen in schema13 humanity link: "+citizenId));c.restoreHumanity(skill,householdId);}
        n=CodecIO.checkedCount(in.readInt(),100000,"settlement civilization extensions");for(int i=0;i<n;i++){long settlementId=in.readLong();SettlementCivilizationState c=state.findSettlementCivilization(settlementId).orElseThrow(()->new IOException("unknown settlement civilization extension: "+settlementId));double quarantine=in.readDouble();EnumMap<KnowledgeDomain,Double> knowledge=new EnumMap<>(KnowledgeDomain.class);for(KnowledgeDomain d:KnowledgeDomain.values())knowledge.put(d,in.readDouble());c.restoreExtended(quarantine,knowledge);}
        n=CodecIO.checkedCount(in.readInt(),10000,"faction civilization extensions");for(int i=0;i<n;i++){long factionId=in.readLong();FactionCivilizationState c=state.findFactionCivilization(factionId).orElseThrow(()->new IOException("unknown faction civilization extension: "+factionId));c.restoreExtended(in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble(),in.readDouble());}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_HOUSEHOLDS,"households");for(int i=0;i<n;i++){long id=in.readLong(),faction=in.readLong(),settlement=in.readLong(),founded=in.readLong();boolean active=in.readBoolean();double wealth=in.readDouble();String home=CodecIO.readString(in);int mc=CodecIO.checkedCount(in.readInt(),HouseholdState.MAX_NAMED_MEMBERS,"household members");List<Long> members=new ArrayList<>();for(int j=0;j<mc;j++)members.add(in.readLong());int cc=CodecIO.checkedCount(in.readInt(),HouseholdState.MAX_CHILDREN,"household children");List<DependentChild> children=new ArrayList<>();for(int j=0;j<cc;j++){DependentChild child=new DependentChild(in.readLong(),in.readLong(),in.readLong(),in.readLong());child.restoreAdoptiveParents(in.readLong(),in.readLong());children.add(child);}HouseholdState h=new HouseholdState(id,faction,settlement,founded);h.restore(members,children,wealth,home,active);state.addHousehold(h);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_EPIDEMICS,"epidemics");for(int i=0;i<n;i++){long id=in.readLong(),settlement=in.readLong(),start=in.readLong();String disease=CodecIO.readString(in);double severity=in.readDouble(),infected=in.readDouble();int deaths=CodecIO.checkedCount(in.readInt(),100000000,"epidemic deaths");long last=in.readLong();boolean active=in.readBoolean();EpidemicRecord e=new EpidemicRecord(id,settlement,start,disease,severity,infected);e.restore(severity,infected,deaths,last,active);state.addEpidemic(e);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_MIGRATIONS,"migration groups");for(int i=0;i<n;i++){long id=in.readLong(),origin=in.readLong(),source=in.readLong(),target=in.readLong(),camp=in.readLong(),created=in.readLong();int people=CodecIO.checkedCount(in.readInt(),1000000,"migration people");MigrationReason reason=MigrationReason.values()[CodecIO.enumOrdinal(in.readInt(),MigrationReason.values().length,"migration reason")];MigrationStatus status=MigrationStatus.values()[CodecIO.enumOrdinal(in.readInt(),MigrationStatus.values().length,"migration status")];double progress=in.readDouble(),food=in.readDouble(),health=in.readDouble();int hc=CodecIO.checkedCount(in.readInt(),8,"migration households");List<Long> households=new ArrayList<>();for(int j=0;j<hc;j++)households.add(in.readLong());MigrationGroup g=new MigrationGroup(id,origin,source,target,created,Math.max(1,people),reason);g.restore(target,camp,people,status,progress,food,health,households);state.addMigrationGroup(g);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_JUSTICE_CASES,"justice cases");for(int i=0;i<n;i++){long id=in.readLong(),faction=in.readLong(),settlement=in.readLong(),opened=in.readLong();String accused=CodecIO.readString(in);CrimeType crime=CrimeType.values()[CodecIO.enumOrdinal(in.readInt(),CrimeType.values().length,"justice crime")];JusticeStatus status=JusticeStatus.values()[CodecIO.enumOrdinal(in.readInt(),JusticeStatus.values().length,"justice status")];SentenceType sentence=SentenceType.values()[CodecIO.enumOrdinal(in.readInt(),SentenceType.values().length,"sentence")];double fine=in.readDouble();long release=in.readLong();JusticeCase j=new JusticeCase(id,faction,settlement,opened,accused,crime);j.restore(status,sentence,fine,release);state.addJusticeCase(j);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_HIDDEN_CACHES,"hidden caches");for(int i=0;i<n;i++){long id=in.readLong(),faction=in.readLong(),settlement=in.readLong(),created=in.readLong();SimPosition pos=CodecIO.readPosition(in);EnumMap<ResourceType,Double> goods=new EnumMap<>(ResourceType.class);for(int ri=0;ri<CodecIO.resourceCount(version);ri++)goods.put(ResourceType.values()[ri],in.readDouble());long discoveredByFaction=in.readLong();boolean recovered=in.readBoolean();HiddenCache c=new HiddenCache(id,faction,settlement,created,pos,goods);c.restore(discoveredByFaction,recovered);state.addHiddenCache(c);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_PIRATE_BANDS,"pirate bands");for(int i=0;i<n;i++){long id=in.readLong(),origin=in.readLong(),created=in.readLong();SimPosition pos=CodecIO.readPosition(in);int strength=CodecIO.checkedCount(in.readInt(),100000,"pirate strength");double morale=in.readDouble(),loot=in.readDouble();boolean active=in.readBoolean();PirateBand b=new PirateBand(id,origin,created,pos,Math.max(1,strength));b.restore(pos,strength,morale,loot,active);state.addPirateBand(b);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_DIPLOMATIC_MARRIAGES,"diplomatic marriages");for(int i=0;i<n;i++){DiplomaticMarriage m=new DiplomaticMarriage(in.readLong(),in.readLong(),in.readLong(),in.readLong(),in.readLong(),in.readLong());m.restoreActive(in.readBoolean());state.addDiplomaticMarriage(m);}
        n=CodecIO.checkedCount(in.readInt(),10000,"dynasties");for(int i=0;i<n;i++){long faction=in.readLong(),founded=in.readLong();String house=CodecIO.readString(in);long ruler=in.readLong(),heir=in.readLong(),regent=in.readLong();double prestige=in.readDouble();boolean crisis=in.readBoolean();long since=in.readLong();int generation=CodecIO.checkedCount(in.readInt(),100000,"dynasty generation");long lastSuccession=in.readLong();DynastyState d=new DynastyState(faction,founded,house);d.restore(ruler,heir,regent,prestige,crisis,since,Math.max(1,generation),lastSuccession);state.restoreDynasty(d);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_CIVIC_EVENTS,"civic events");for(int i=0;i<n;i++){long id=in.readLong(),faction=in.readLong(),settlement=in.readLong(),start=in.readLong(),end=in.readLong();CivicEventType type=CivicEventType.values()[CodecIO.enumOrdinal(in.readInt(),CivicEventType.values().length,"civic event type")];String title=CodecIO.readString(in);double attendance=in.readDouble(),intensity=in.readDouble();boolean active=in.readBoolean();CivicEvent e=new CivicEvent(id,faction,settlement,start,end,type,title,intensity);e.restore(attendance,intensity,active);state.addCivicEvent(e);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_INTELLIGENCE_OPERATIONS,"intelligence operations");for(int i=0;i<n;i++){long id=in.readLong(),source=in.readLong(),target=in.readLong(),start=in.readLong(),agent=in.readLong();IntelligenceOperationType type=IntelligenceOperationType.values()[CodecIO.enumOrdinal(in.readInt(),IntelligenceOperationType.values().length,"intelligence operation type")];double progress=in.readDouble(),secrecy=in.readDouble(),quality=in.readDouble();boolean discovered=in.readBoolean(),active=in.readBoolean();IntelligenceOperation o=new IntelligenceOperation(id,source,target,start,agent,type);o.restore(progress,secrecy,quality,discovered,active);state.addIntelligenceOperation(o);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_PROPAGANDA_CAMPAIGNS,"propaganda campaigns");for(int i=0;i<n;i++){long id=in.readLong(),faction=in.readLong(),settlement=in.readLong(),start=in.readLong(),end=in.readLong();PropagandaTheme theme=PropagandaTheme.values()[CodecIO.enumOrdinal(in.readInt(),PropagandaTheme.values().length,"propaganda theme")];double intensity=in.readDouble(),reach=in.readDouble();boolean active=in.readBoolean();PropagandaCampaign c=new PropagandaCampaign(id,faction,settlement,start,end,theme,intensity);c.restore(intensity,reach,active);state.addPropagandaCampaign(c);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_RUIN_SITES,"ruin sites");for(int i=0;i<n;i++){long id=in.readLong(),settlement=in.readLong(),faction=in.readLong(),created=in.readLong();SimPosition position=CodecIO.readPosition(in);String name=CodecIO.readString(in),cause=CodecIO.readString(in);double preservation=in.readDouble();boolean looted=in.readBoolean(),reclaimed=in.readBoolean();RuinSite r=new RuinSite(id,settlement,faction,created,position,name,cause);r.restore(preservation,looted,reclaimed);state.addRuinSite(r);}
        n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_ASSISTANCE_TASKS,"assistance tasks");for(int i=0;i<n;i++){long id=in.readLong(),faction=in.readLong(),settlement=in.readLong(),created=in.readLong(),expires=in.readLong();AssistanceTaskType type=AssistanceTaskType.values()[CodecIO.enumOrdinal(in.readInt(),AssistanceTaskType.values().length,"assistance task type")];String cause=CodecIO.readString(in);double initial=in.readDouble(),remaining=in.readDouble();AssistanceTaskStatus status=AssistanceTaskStatus.values()[CodecIO.enumOrdinal(in.readInt(),AssistanceTaskStatus.values().length,"assistance task status")];AssistanceTask task=new AssistanceTask(id,faction,settlement,created,expires,type,cause,initial);task.restore(remaining,status);state.addAssistanceTask(task);}
    }

public static void writeV14PirateHideouts(DataOutputStream out,SimulationState state)throws IOException{
        var hideouts=new ArrayList<>(state.pirateHideouts());hideouts.sort(Comparator.comparingLong(PirateHideout::id));out.writeInt(hideouts.size());for(PirateHideout h:hideouts){out.writeLong(h.id());out.writeLong(h.bandId());out.writeLong(h.originSettlementId());out.writeLong(h.createdDay());CodecIO.writePosition(out,h.position());out.writeDouble(h.defense());out.writeDouble(h.storedLoot());out.writeLong(h.discoveredByFactionId());out.writeBoolean(h.active());out.writeBoolean(h.destroyed());}
    }

public static void readV14PirateHideouts(DataInputStream in,SimulationState state)throws IOException{
        int n=CodecIO.checkedCount(in.readInt(),SimulationState.MAX_PIRATE_HIDEOUTS,"pirate hideouts");for(int i=0;i<n;i++){long id=in.readLong(),band=in.readLong(),origin=in.readLong(),created=in.readLong();SimPosition pos=CodecIO.readPosition(in);double defense=in.readDouble(),loot=in.readDouble();long discovered=in.readLong();boolean active=in.readBoolean(),destroyed=in.readBoolean();PirateHideout h=new PirateHideout(id,band,origin,created,pos);h.restore(defense,loot,discovered,active,destroyed);state.addPirateHideout(h);}
    }

}
