package dev.livingrealms.sim.civilian;
public enum CitizenActivity { WORK_FARM, WORK_MINE, WORK_FORESTRY, HUNT, WORK_FISHERY, CRAFT, BUTCHER, CARPENTRY, TRADE, BUILD, ADMINISTER, PATROL, HEAL, WORSHIP, STUDY, TEACH, SAIL, DOCK_WORK, INFILTRATE, REST, SOCIALIZE, IDLE }
