package dev.livingrealms.sim.dialogue;
public enum DialogueTopic {
    NONE, SELF, AGE, JOB, FAMILY, HEALTH,
    BANDITS, DANGER, RULER, DYNASTY, SETTLEMENT, FACTION, POLITICS, LAW, CRIME, TAX,
    FOOD, WATER, RESOURCES, TRADE, PRICE, TECHNOLOGY, SCHOOL, WAR, ARMY, GUARDS, ROUTE, MIGRATION, CULTURE, RELIGION, HISTORY, RUMOR, CALENDAR,
    EVENT, LOCATION, PLAYER
}
