package dev.livingrealms.sim.dialogue;
public enum DialogueIntent {
    GREET,
    ASK_SELF, ASK_AGE, ASK_JOB, ASK_FAMILY, ASK_HEALTH,
    ASK_DANGER, ASK_DIRECTION, ASK_SOURCE,
    ASK_RULER, ASK_DYNASTY, ASK_SETTLEMENT, ASK_FACTION, ASK_POLITICS, ASK_LAW, ASK_CRIME, ASK_TAX,
    ASK_FOOD, ASK_WATER, ASK_RESOURCES, ASK_TRADE, ASK_PRICE, ASK_TECHNOLOGY, ASK_SCHOOL,
    ASK_WAR, ASK_ARMY, ASK_GUARDS, ASK_ROUTE, ASK_MIGRATION, ASK_CULTURE, ASK_RELIGION, ASK_HISTORY, ASK_RUMOR, ASK_CALENDAR,
    ASK_RECENT_EVENT, ASK_OPINION, ASK_HELP,
    TRADE, GIVE_GIFT, COMPLIMENT, APOLOGIZE, REPORT_CRIME, REPORT_DANGER, PROVIDE_INFORMATION, THREATEN, INSULT, GOODBYE, UNKNOWN
}
