package dev.livingrealms.sim.dialogue;

import java.util.*;

/** Longest-phrase-wins intent bindings for {@link NaturalLanguageDialogueEngine#parse}. */
final class DialoguePhraseTable {
    private DialoguePhraseTable() {}

    record Match(String phrase, DialogueIntent intent, DialogueTopic topic, String subject, boolean dynamicResource) {}

    private static final List<Match> RULES = build();

    static Match longest(String normalizedInput) {
        Match best = null;
        for (Match candidate : RULES) {
            if (!normalizedInput.contains(candidate.phrase())) continue;
            if (best == null || candidate.phrase().length() > best.phrase().length()) best = candidate;
        }
        return best;
    }

    private static List<Match> build() {
        List<Match> rules = new ArrayList<>();
        add(rules, "ik wil een misdaad melden", DialogueIntent.REPORT_CRIME, DialogueTopic.CRIME, "reported-crime");
        add(rules, "ik meld een misdaad", DialogueIntent.REPORT_CRIME, DialogueTopic.CRIME, "reported-crime");
        add(rules, "report a crime", DialogueIntent.REPORT_CRIME, DialogueTopic.CRIME, "reported-crime");
        add(rules, "ik wil gevaar melden", DialogueIntent.REPORT_DANGER, DialogueTopic.DANGER, "reported-danger");
        add(rules, "report danger", DialogueIntent.REPORT_DANGER, DialogueTopic.DANGER, "reported-danger");
        add(rules, "ik hoorde dat", DialogueIntent.PROVIDE_INFORMATION, DialogueTopic.RUMOR, "player-information");
        add(rules, "i heard that", DialogueIntent.PROVIDE_INFORMATION, DialogueTopic.RUMOR, "player-information");
        add(rules, "ik weet dat", DialogueIntent.PROVIDE_INFORMATION, DialogueTopic.RUMOR, "player-information");
        add(rules, "i know that", DialogueIntent.PROVIDE_INFORMATION, DialogueTopic.RUMOR, "player-information");
        add(rules, "ik zag dat", DialogueIntent.PROVIDE_INFORMATION, DialogueTopic.RUMOR, "player-information");
        add(rules, "i saw that", DialogueIntent.PROVIDE_INFORMATION, DialogueTopic.RUMOR, "player-information");
        add(rules, "wat vind je van mij", DialogueIntent.ASK_OPINION, DialogueTopic.PLAYER, "player");
        add(rules, "what do you think of me", DialogueIntent.ASK_OPINION, DialogueTopic.PLAYER, "player");
        add(rules, "bedankt voor je werk", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "present for you", DialogueIntent.GIVE_GIFT, DialogueTopic.PLAYER, "player");
        add(rules, "het spijt me", DialogueIntent.APOLOGIZE, DialogueTopic.PLAYER, "player");
        add(rules, "i apologize", DialogueIntent.APOLOGIZE, DialogueTopic.PLAYER, "player");
        add(rules, "ik maak je af", DialogueIntent.THREATEN, DialogueTopic.PLAYER, "player");
        add(rules, "kill you", DialogueIntent.THREATEN, DialogueTopic.PLAYER, "player");
        add(rules, "hoe sterk is het leger", DialogueIntent.ASK_ARMY, DialogueTopic.ARMY, "army");
        add(rules, "how strong is the army", DialogueIntent.ASK_ARMY, DialogueTopic.ARMY, "army");
        add(rules, "how big is the army", DialogueIntent.ASK_ARMY, DialogueTopic.ARMY, "army");
        add(rules, "hoe groot is het leger", DialogueIntent.ASK_ARMY, DialogueTopic.ARMY, "army");
        add(rules, "wie volgt de koning", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "welk koninkrijk", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "which kingdom", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "trade partner", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "partner");
        add(rules, "handelspartner", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "partner");
        add(rules, "royal court", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "koninklijk hof", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "who rules the royal court", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "crime rate", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "crime");
        add(rules, "crime here", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "crime");
        add(rules, "misdaad hier", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "crime");
        add(rules, "criminals here", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "crime");
        add(rules, "zijn er criminelen", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "crime");
        add(rules, "staat er een premie op mij", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "wanted");
        add(rules, "bounty on me", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "wanted");
        add(rules, "ben ik gezocht", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "wanted");
        add(rules, "am i wanted", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "wanted");
        add(rules, "vertel over jezelf", DialogueIntent.ASK_SELF, DialogueTopic.SELF, "self");
        add(rules, "tell me about yourself", DialogueIntent.ASK_SELF, DialogueTopic.SELF, "self");
        add(rules, "hoe oud ben je", DialogueIntent.ASK_AGE, DialogueTopic.AGE, "age");
        add(rules, "how old are you", DialogueIntent.ASK_AGE, DialogueTopic.AGE, "age");
        add(rules, "wat is je leeftijd", DialogueIntent.ASK_AGE, DialogueTopic.AGE, "age");
        add(rules, "hoe gaat het met je", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "are you ill", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "what do you do", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "your job", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "hoe gaat de handel", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "trade here", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "market here", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "trade route", DialogueIntent.ASK_ROUTE, DialogueTopic.ROUTE, "route");
        add(rules, "handelsroute", DialogueIntent.ASK_ROUTE, DialogueTopic.ROUTE, "route");
        add(rules, "ik wil handelen", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "trade with me", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "i want to buy", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "i want to sell", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "open trade", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "where can i eat", DialogueIntent.ASK_FOOD, DialogueTopic.FOOD, "food");
        add(rules, "buy food", DialogueIntent.ASK_FOOD, DialogueTopic.FOOD, "food");
        add(rules, "voedsel kopen", DialogueIntent.ASK_FOOD, DialogueTopic.FOOD, "food");
        add(rules, "water shortage", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "clean water", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "water supply", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "schoon water", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "drinkwater", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "where is the well", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "wat is de datum", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "what day is it", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "what year is it", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "season is it", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "wat is er gebeurd", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "what happened", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "threat nearby", DialogueIntent.ASK_DANGER, DialogueTopic.DANGER, "danger");
        add(rules, "heb je iets gehoord", DialogueIntent.ASK_RUMOR, DialogueTopic.RUMOR, "rumor");
        add(rules, "heard anything", DialogueIntent.ASK_RUMOR, DialogueTopic.RUMOR, "rumor");
        add(rules, "royal house", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "koningshuis", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "where do you live", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "this village", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "this town", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "this city", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "de nederzetting", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "guard patrol", DialogueIntent.ASK_GUARDS, DialogueTopic.GUARDS, "guards");
        add(rules, "people leaving", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "people arriving", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "language here", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "taal hier", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "education here", DialogueIntent.ASK_SCHOOL, DialogueTopic.SCHOOL, "school");
        add(rules, "school here", DialogueIntent.ASK_SCHOOL, DialogueTopic.SCHOOL, "school");
        add(rules, "water source", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "grondstoffen", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "anything i can do", DialogueIntent.ASK_HELP, DialogueTopic.EVENT, "help");
        add(rules, "wat kan ik doen", DialogueIntent.ASK_HELP, DialogueTopic.EVENT, "help");
        add(rules, "can i help", DialogueIntent.ASK_HELP, DialogueTopic.EVENT, "help");
        add(rules, "need help", DialogueIntent.ASK_HELP, DialogueTopic.EVENT, "help");
        add(rules, "hulp nodig", DialogueIntent.ASK_HELP, DialogueTopic.EVENT, "help");
        add(rules, "kan ik helpen", DialogueIntent.ASK_HELP, DialogueTopic.EVENT, "help");
        add(rules, "i saw a murder", DialogueIntent.REPORT_CRIME, DialogueTopic.CRIME, "reported-crime");
        add(rules, "i saw a theft", DialogueIntent.REPORT_CRIME, DialogueTopic.CRIME, "reported-crime");
        add(rules, "ik zag een moord", DialogueIntent.REPORT_CRIME, DialogueTopic.CRIME, "reported-crime");
        add(rules, "ik zag een diefstal", DialogueIntent.REPORT_CRIME, DialogueTopic.CRIME, "reported-crime");
        add(rules, "i saw bandits", DialogueIntent.REPORT_DANGER, DialogueTopic.DANGER, "reported-danger");
        add(rules, "i saw enemies", DialogueIntent.REPORT_DANGER, DialogueTopic.DANGER, "reported-danger");
        add(rules, "ik zag bandieten", DialogueIntent.REPORT_DANGER, DialogueTopic.DANGER, "reported-danger");
        add(rules, "ik zag vijanden", DialogueIntent.REPORT_DANGER, DialogueTopic.DANGER, "reported-danger");
        add(rules, "er is gevaar", DialogueIntent.REPORT_DANGER, DialogueTopic.DANGER, "reported-danger");
        add(rules, "you are great", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "you are kind", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "you're kind", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "nice work", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "goed gedaan", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "je bent geweldig", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "je bent aardig", DialogueIntent.COMPLIMENT, DialogueTopic.PLAYER, "player");
        add(rules, "mijn excuses", DialogueIntent.APOLOGIZE, DialogueTopic.PLAYER, "player");
        add(rules, "apologies", DialogueIntent.APOLOGIZE, DialogueTopic.PLAYER, "player");
        add(rules, "voor jou", DialogueIntent.GIVE_GIFT, DialogueTopic.PLAYER, "player");
        add(rules, "cadeau", DialogueIntent.GIVE_GIFT, DialogueTopic.PLAYER, "player");
        add(rules, "geschenk", DialogueIntent.GIVE_GIFT, DialogueTopic.PLAYER, "player");
        add(rules, "tot ziens", DialogueIntent.GOODBYE, DialogueTopic.NONE, "");
        add(rules, "goodbye", DialogueIntent.GOODBYE, DialogueTopic.NONE, "");
        add(rules, "see you", DialogueIntent.GOODBYE, DialogueTopic.NONE, "");
        add(rules, "later", DialogueIntent.GOODBYE, DialogueTopic.NONE, "");
        add(rules, "doei", DialogueIntent.GOODBYE, DialogueTopic.NONE, "");
        add(rules, "bye", DialogueIntent.GOODBYE, DialogueTopic.NONE, "");
        add(rules, "hurt you", DialogueIntent.THREATEN, DialogueTopic.PLAYER, "player");
        add(rules, "ik vermoord", DialogueIntent.THREATEN, DialogueTopic.PLAYER, "player");
        add(rules, "bedreig", DialogueIntent.THREATEN, DialogueTopic.PLAYER, "player");
        add(rules, "threat", DialogueIntent.THREATEN, DialogueTopic.PLAYER, "player");
        add(rules, "haat je", DialogueIntent.INSULT, DialogueTopic.PLAYER, "player");
        add(rules, "idiot", DialogueIntent.INSULT, DialogueTopic.PLAYER, "player");
        add(rules, "stupid", DialogueIntent.INSULT, DialogueTopic.PLAYER, "player");
        add(rules, "moron", DialogueIntent.INSULT, DialogueTopic.PLAYER, "player");
        add(rules, "sukkel", DialogueIntent.INSULT, DialogueTopic.PLAYER, "player");
        add(rules, "stom", DialogueIntent.INSULT, DialogueTopic.PLAYER, "player");
        add(rules, "idioot", DialogueIntent.INSULT, DialogueTopic.PLAYER, "player");
        addPrice(rules, "how much is");
        addPrice(rules, "price of");
        addPrice(rules, "prijs van");
        addPrice(rules, "hoe duur");
        addPrice(rules, "wat kost");
        add(rules, "familie", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "family", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "gezin", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "kinderen", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "children", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "parents", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "ouders", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "husband", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "wife", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "sibling", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "broer", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "zus", DialogueIntent.ASK_FAMILY, DialogueTopic.FAMILY, "family");
        add(rules, "gezondheid", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "genezer", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "dokter", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "ziekte", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "disease", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "healer", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "health", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "sick", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "ziek", DialogueIntent.ASK_HEALTH, DialogueTopic.HEALTH, "health");
        add(rules, "belastingen", DialogueIntent.ASK_TAX, DialogueTopic.TAX, "tax");
        add(rules, "belasting", DialogueIntent.ASK_TAX, DialogueTopic.TAX, "tax");
        add(rules, "taxes", DialogueIntent.ASK_TAX, DialogueTopic.TAX, "tax");
        add(rules, "tribute", DialogueIntent.ASK_TAX, DialogueTopic.TAX, "tax");
        add(rules, "tribut", DialogueIntent.ASK_TAX, DialogueTopic.TAX, "tax");
        add(rules, "tax", DialogueIntent.ASK_TAX, DialogueTopic.TAX, "tax");
        add(rules, "rechtbank", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "gevangenis", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "punishment", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "prison", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "wetten", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "laws", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "straf", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "court", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "law", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "wet", DialogueIntent.ASK_LAW, DialogueTopic.LAW, "law");
        add(rules, "erfgenaam", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "successor", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "opvolger", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "dynastie", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "dynasty", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "heir", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "regent", DialogueIntent.ASK_DYNASTY, DialogueTopic.DYNASTY, "dynasty");
        add(rules, "government", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "politics", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "regering", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "bestuur", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "politiek", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "rule here", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "theocr", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "tirann", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "democr", DialogueIntent.ASK_POLITICS, DialogueTopic.POLITICS, "politics");
        add(rules, "koningin", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "koning", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "heerser", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "queen", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "ruler", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "mayor", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "king", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "leider", DialogueIntent.ASK_RULER, DialogueTopic.RULER, "ruler");
        add(rules, "welke factie", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "welk rijk", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "jouw rijk", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "kingdom", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "faction", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "realm", DialogueIntent.ASK_FACTION, DialogueTopic.FACTION, "faction");
        add(rules, "hoe is het hier", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "waar woon je", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "deze stad", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "dit dorp", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "settlement", DialogueIntent.ASK_SETTLEMENT, DialogueTopic.SETTLEMENT, "settlement");
        add(rules, "legersterkte", DialogueIntent.ASK_ARMY, DialogueTopic.ARMY, "army");
        add(rules, "army strength", DialogueIntent.ASK_ARMY, DialogueTopic.ARMY, "army");
        add(rules, "patrouille", DialogueIntent.ASK_GUARDS, DialogueTopic.GUARDS, "guards");
        add(rules, "wachters", DialogueIntent.ASK_GUARDS, DialogueTopic.GUARDS, "guards");
        add(rules, "guards", DialogueIntent.ASK_GUARDS, DialogueTopic.GUARDS, "guards");
        add(rules, "soldiers", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "soldaten", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "beleger", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "siege", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "enemy", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "vijand", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "oorlog", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "war", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "army", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "leger", DialogueIntent.ASK_WAR, DialogueTopic.WAR, "war");
        add(rules, "vertrekken mensen", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "migreren", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "migration", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "refugee", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "vluchteling", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "migratie", DialogueIntent.ASK_MIGRATION, DialogueTopic.MIGRATION, "migration");
        add(rules, "tradition", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "traditie", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "gewoonte", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "custom", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "dialect", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "culture", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "cultuur", DialogueIntent.ASK_CULTURE, DialogueTopic.CULTURE, "culture");
        add(rules, "religion", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "religie", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "worship", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "priester", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "priest", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "tempel", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "temple", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "geloof", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "faith", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "god", DialogueIntent.ASK_RELIGION, DialogueTopic.RELIGION, "religion");
        add(rules, "geschiedenis", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "history", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "legend", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "legende", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "monument", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "long ago", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "vroeger", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "held", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "hero", DialogueIntent.ASK_HISTORY, DialogueTopic.HISTORY, "history");
        add(rules, "gerucht", DialogueIntent.ASK_RUMOR, DialogueTopic.RUMOR, "rumor");
        add(rules, "gossip", DialogueIntent.ASK_RUMOR, DialogueTopic.RUMOR, "rumor");
        add(rules, "rumour", DialogueIntent.ASK_RUMOR, DialogueTopic.RUMOR, "rumor");
        add(rules, "rumor", DialogueIntent.ASK_RUMOR, DialogueTopic.RUMOR, "rumor");
        add(rules, "roddel", DialogueIntent.ASK_RUMOR, DialogueTopic.RUMOR, "rumor");
        add(rules, "grondstof", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "resources", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "resource", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "waterbron", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "wood", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "hout", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "iron", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "ijzer", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "mine", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "mijn", DialogueIntent.ASK_RESOURCES, DialogueTopic.RESOURCES, "resources");
        add(rules, "onderwijs", DialogueIntent.ASK_SCHOOL, DialogueTopic.SCHOOL, "school");
        add(rules, "opleiding", DialogueIntent.ASK_SCHOOL, DialogueTopic.SCHOOL, "school");
        add(rules, "teacher", DialogueIntent.ASK_SCHOOL, DialogueTopic.SCHOOL, "school");
        add(rules, "leraar", DialogueIntent.ASK_SCHOOL, DialogueTopic.SCHOOL, "school");
        add(rules, "school", DialogueIntent.ASK_SCHOOL, DialogueTopic.SCHOOL, "school");
        add(rules, "technologie", DialogueIntent.ASK_TECHNOLOGY, DialogueTopic.TECHNOLOGY, "technology");
        add(rules, "technology", DialogueIntent.ASK_TECHNOLOGY, DialogueTopic.TECHNOLOGY, "technology");
        add(rules, "invention", DialogueIntent.ASK_TECHNOLOGY, DialogueTopic.TECHNOLOGY, "technology");
        add(rules, "uitvinding", DialogueIntent.ASK_TECHNOLOGY, DialogueTopic.TECHNOLOGY, "technology");
        add(rules, "kennis", DialogueIntent.ASK_TECHNOLOGY, DialogueTopic.TECHNOLOGY, "technology");
        add(rules, "knowledge", DialogueIntent.ASK_TECHNOLOGY, DialogueTopic.TECHNOLOGY, "technology");
        add(rules, "economie", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "economy", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "prices", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "prijzen hier", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "markt hier", DialogueIntent.ASK_TRADE, DialogueTopic.TRADE, "market");
        add(rules, "open handel", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "handel met mij", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "wil verkopen", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "wil kopen", DialogueIntent.TRADE, DialogueTopic.TRADE, "market");
        add(rules, "eten kopen", DialogueIntent.ASK_FOOD, DialogueTopic.FOOD, "food");
        add(rules, "food", DialogueIntent.ASK_FOOD, DialogueTopic.FOOD, "food");
        add(rules, "welk seizoen", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "welke dag", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "welk jaar", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "date today", DialogueIntent.ASK_CALENDAR, DialogueTopic.CALENDAR, "calendar");
        add(rules, "route to", DialogueIntent.ASK_ROUTE, DialogueTopic.ROUTE, "route");
        add(rules, "road to", DialogueIntent.ASK_ROUTE, DialogueTopic.ROUTE, "route");
        add(rules, "weg naar", DialogueIntent.ASK_ROUTE, DialogueTopic.ROUTE, "route");
        add(rules, "welke weg", DialogueIntent.ASK_ROUTE, DialogueTopic.ROUTE, "route");
        add(rules, "welke route", DialogueIntent.ASK_ROUTE, DialogueTopic.ROUTE, "route");
        add(rules, "recently", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "yesterday", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "gisteren", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "vandaag", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "recent", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "news", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "nieuws", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "today", DialogueIntent.ASK_RECENT_EVENT, DialogueTopic.EVENT, "recent");
        add(rules, "brigand", DialogueIntent.ASK_DANGER, DialogueTopic.BANDITS, "bandits");
        add(rules, "raiders", DialogueIntent.ASK_DANGER, DialogueTopic.BANDITS, "bandits");
        add(rules, "rovers", DialogueIntent.ASK_DANGER, DialogueTopic.BANDITS, "bandits");
        add(rules, "bandiet", DialogueIntent.ASK_DANGER, DialogueTopic.BANDITS, "bandits");
        add(rules, "bandit", DialogueIntent.ASK_DANGER, DialogueTopic.BANDITS, "bandits");
        add(rules, "attack", DialogueIntent.ASK_DANGER, DialogueTopic.DANGER, "danger");
        add(rules, "aanval", DialogueIntent.ASK_DANGER, DialogueTopic.DANGER, "danger");
        add(rules, "danger", DialogueIntent.ASK_DANGER, DialogueTopic.DANGER, "danger");
        add(rules, "gevaar", DialogueIntent.ASK_DANGER, DialogueTopic.DANGER, "danger");
        add(rules, "safe", DialogueIntent.ASK_DANGER, DialogueTopic.DANGER, "danger");
        add(rules, "veilig", DialogueIntent.ASK_DANGER, DialogueTopic.DANGER, "danger");
        add(rules, "wie ben je", DialogueIntent.ASK_SELF, DialogueTopic.SELF, "self");
        add(rules, "who are you", DialogueIntent.ASK_SELF, DialogueTopic.SELF, "self");
        add(rules, "hoe heet je", DialogueIntent.ASK_SELF, DialogueTopic.SELF, "self");
        add(rules, "your name", DialogueIntent.ASK_SELF, DialogueTopic.SELF, "self");
        add(rules, "jouw naam", DialogueIntent.ASK_SELF, DialogueTopic.SELF, "self");
        add(rules, "wat doe je", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "werk je", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "beroep", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "jouw werk", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "occupation", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "profession", DialogueIntent.ASK_JOB, DialogueTopic.JOB, "job");
        add(rules, "your age", DialogueIntent.ASK_AGE, DialogueTopic.AGE, "age");
        add(rules, "criminaliteit", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "crime");
        add(rules, "ben ik wanted", DialogueIntent.ASK_CRIME, DialogueTopic.CRIME, "wanted");
        add(rules, "mening over mij", DialogueIntent.ASK_OPINION, DialogueTopic.PLAYER, "player");
        add(rules, "denk je van mij", DialogueIntent.ASK_OPINION, DialogueTopic.PLAYER, "player");
        add(rules, "opinion of me", DialogueIntent.ASK_OPINION, DialogueTopic.PLAYER, "player");
        add(rules, "gift", DialogueIntent.GIVE_GIFT, DialogueTopic.PLAYER, "player");
        add(rules, "sorry", DialogueIntent.APOLOGIZE, DialogueTopic.PLAYER, "player");
        add(rules, "watertekort", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "waar is de put", DialogueIntent.ASK_WATER, DialogueTopic.WATER, "water");
        add(rules, "greetings", DialogueIntent.GREET, DialogueTopic.NONE, "");
        add(rules, "goedendag", DialogueIntent.GREET, DialogueTopic.NONE, "");
        add(rules, "hello", DialogueIntent.GREET, DialogueTopic.NONE, "");
        add(rules, "hallo", DialogueIntent.GREET, DialogueTopic.NONE, "");
        add(rules, "hoi", DialogueIntent.GREET, DialogueTopic.NONE, "");
        add(rules, "hey", DialogueIntent.GREET, DialogueTopic.NONE, "");
        rules.sort(Comparator.comparingInt((Match r) -> r.phrase().length()).reversed());
        return rules;
    }

    private static void add(List<Match> rules, String phrase, DialogueIntent intent, DialogueTopic topic, String subject) {
        rules.add(new Match(phrase, intent, topic, subject, false));
    }

    private static void addPrice(List<Match> rules, String phrase) {
        rules.add(new Match(phrase, DialogueIntent.ASK_PRICE, DialogueTopic.PRICE, "", true));
    }
}
