package dev.livingrealms.sim.dialogue;

import dev.livingrealms.sim.civilian.CitizenRole;
import dev.livingrealms.sim.civilization.*;
import dev.livingrealms.sim.faction.*;
import dev.livingrealms.sim.economy.LocalMarketEngine;
import dev.livingrealms.sim.economy.MarketEngine;
import dev.livingrealms.sim.transport.TransportRoute;
import dev.livingrealms.sim.social.*;
import dev.livingrealms.sim.society.WorldCauseExplainer;
import dev.livingrealms.sim.world.*;
import java.text.Normalizer;
import java.util.*;

/**
 * Deterministic no-LLM conversation engine. Free text is normalized into intents/topics/entities,
 * short context resolves follow-ups, and every factual answer is grounded in canonical state or
 * the individual citizen's bounded knowledge.
 */
public final class NaturalLanguageDialogueEngine {
    public DialogueResult respond(SimulationState state,SocialCitizen citizen,String playerKey,String input,DialogueContext context){
        Objects.requireNonNull(state);Objects.requireNonNull(citizen);if(playerKey==null||playerKey.isBlank())throw new IllegalArgumentException("playerKey");if(input==null)input="";if(context==null)context=new DialogueContext();
        Parsed parsed=parse(input,context);long day=state.clock().day();Faction faction=state.findFaction(citizen.factionId()).orElse(null);Settlement settlement=state.findSettlement(citizen.settlementId()).orElse(null);
        if(faction==null||settlement==null)return new DialogueResult(parsed.intent,parsed.topic,"I don't know where I belong anymore.",List.of());
        List<DialogueAction> actions=new ArrayList<>();String response=switch(parsed.intent){
            case GREET -> compose(citizen,day,"greet",List.of("Hello","Good to see another face","Greetings")) + ", traveler.";
            case ASK_SELF -> answerSelf(citizen,settlement,faction,day);
            case ASK_AGE -> answerAge(citizen,day);
            case ASK_JOB -> answerJob(citizen,settlement,day);
            case ASK_FAMILY -> answerFamily(state,citizen,day);
            case ASK_HEALTH -> answerHealth(state,citizen,settlement,day);
            case ASK_RULER -> answerRuler(citizen,faction,day);
            case ASK_DYNASTY -> answerDynasty(state,citizen,faction,day);
            case ASK_SETTLEMENT -> answerSettlement(state,citizen,settlement,faction,day);
            case ASK_FACTION -> answerFaction(state,citizen,faction,day);
            case ASK_POLITICS -> answerPolitics(state,citizen,faction,day);
            case ASK_LAW -> answerLaw(citizen,settlement,faction,day);
            case ASK_CRIME -> answerCrime(state,citizen,settlement,faction,playerKey,parsed.subject,day);
            case ASK_TAX -> answerTax(citizen,faction,day);
            case ASK_FOOD -> answerFood(state,citizen,settlement,faction,day,actions);
            case ASK_WATER -> answerWater(state,citizen,settlement,faction,day);
            case ASK_RESOURCES -> answerResources(state,citizen,settlement,faction,day);
            case ASK_TRADE -> answerTradeState(citizen,settlement,faction,day);
            case ASK_PRICE -> answerPrice(citizen,faction,settlement,parsed.subject,day);
            case ASK_TECHNOLOGY -> answerTechnology(state,citizen,faction,day);
            case ASK_SCHOOL -> answerSchool(state,citizen,settlement,faction,day);
            case ASK_WAR -> answerWar(state,citizen,faction,day,actions);
            case ASK_ARMY -> answerArmy(state,citizen,faction,day);
            case ASK_GUARDS -> answerGuards(state,citizen,settlement,faction,day);
            case ASK_ROUTE -> answerRoute(state,citizen,settlement,day,actions);
            case ASK_MIGRATION -> answerMigration(state,citizen,settlement,faction,day);
            case ASK_CULTURE -> answerCulture(state,citizen,faction,day);
            case ASK_RELIGION -> answerReligion(state,citizen,faction,day);
            case ASK_HISTORY -> answerHistory(state,citizen,faction,settlement,day);
            case ASK_RUMOR -> answerRumor(citizen,day);
            case ASK_CALENDAR -> answerCalendar(citizen,day);
            case ASK_DANGER -> answerDanger(state,citizen,settlement,parsed.topic,day,actions);
            case ASK_DIRECTION -> answerDirection(state,citizen,context,parsed.subject,settlement,day,actions);
            case ASK_SOURCE -> answerSource(citizen,context,day);
            case ASK_RECENT_EVENT -> answerRecent(state,citizen,settlement,day);
            case ASK_OPINION -> answerOpinion(citizen,playerKey,day);
            case ASK_HELP -> answerHelp(state,citizen,settlement,faction,day,actions);
            case TRADE -> {actions.add(new DialogueAction(DialogueActionType.OPEN_TRADE,"settlement:"+settlement.id(),settlement.position(),0));yield compose(citizen,day,"trade",List.of("We can talk prices","If you have coin or goods, we can trade","Let's see what the market will bear"))+".";}
            case GIVE_GIFT -> {actions.add(new DialogueAction(DialogueActionType.ACCEPT_GIFT,playerKey,null,1));yield "If that is for me, hand it over and I will remember it.";}
            case COMPLIMENT -> interaction(state,citizen,playerKey,MemoryType.CONVERSATION,.08,-.03,1.5,"That's kind of you to say.",actions);
            case APOLOGIZE -> interaction(state,citizen,playerKey,MemoryType.CONVERSATION,.04,-.08,.8,"I hear your apology. What happens next will matter more than the words.",actions);
            case REPORT_CRIME -> reportInformation(state,citizen,playerKey,MemoryType.RUMOR,"reported-crime","The player reported a crime nearby.",.72,actions,true);
            case REPORT_DANGER -> reportInformation(state,citizen,playerKey,MemoryType.RUMOR,"reported-danger","The player reported a nearby danger.",.72,actions,true);
            case PROVIDE_INFORMATION -> reportInformation(state,citizen,playerKey,MemoryType.RUMOR,"player-information",summarizeInput(input),.58,actions,false);
            case THREATEN -> interaction(state,citizen,playerKey,MemoryType.THREAT,-.15,.22,-5.0,"Threats travel quickly here.",actions);
            case INSULT -> interaction(state,citizen,playerKey,MemoryType.INSULT,-.09,.12,-2.0,"I won't forget the way you speak to people.",actions);
            case GOODBYE -> compose(citizen,day,"bye",List.of("Safe travels","Until next time","Go carefully"))+".";
            case UNKNOWN -> unknown(citizen,day);
        };
        citizen.remember(new CitizenMemory(day,MemoryType.CONVERSATION,playerKey,"self",summarizeInput(input),settlement.position(),.12,1));
        DialogueTopic topic=parsed.topic==DialogueTopic.NONE?inferTopic(parsed.intent):parsed.topic;String subject=parsed.subject.isBlank()?subjectFor(topic):parsed.subject;context.update(parsed.intent,topic,subject,day);
        return new DialogueResult(parsed.intent,topic,response,actions);
    }

    public Parsed parse(String raw,DialogueContext context){
        Objects.requireNonNull(context);String s=normalize(raw);Set<String> tokens=new LinkedHashSet<>(s.isBlank()?List.of():Arrays.asList(s.split(" ")));
        if(any(s,"doei","tot ziens","goodbye","bye","see you","later"))return p(DialogueIntent.GOODBYE,DialogueTopic.NONE,"");
        if(any(s,"bedreig","ik maak je af","ik vermoord","threat","kill you","hurt you"))return p(DialogueIntent.THREATEN,DialogueTopic.PLAYER,"player");
        if(any(s,"idioot","stom","sukkel","haat je","idiot","stupid","moron"))return p(DialogueIntent.INSULT,DialogueTopic.PLAYER,"player");
        if(any(s,"cadeau","geschenk","gift","voor jou","present for you"))return p(DialogueIntent.GIVE_GIFT,DialogueTopic.PLAYER,"player");
        if(any(s,"sorry","het spijt me","mijn excuses","i apologize","apologies"))return p(DialogueIntent.APOLOGIZE,DialogueTopic.PLAYER,"player");
        if(any(s,"goed gedaan","je bent aardig","je bent geweldig","bedankt voor je werk","nice work","you are kind","you're kind","you are great"))return p(DialogueIntent.COMPLIMENT,DialogueTopic.PLAYER,"player");
        if(any(s,"ik wil een misdaad melden","ik meld een misdaad","ik zag een diefstal","ik zag een moord","report a crime","i saw a theft","i saw a murder"))return p(DialogueIntent.REPORT_CRIME,DialogueTopic.CRIME,"reported-crime");
        if(any(s,"ik wil gevaar melden","ik zag bandieten","ik zag vijanden","er is gevaar","report danger","i saw bandits","i saw enemies"))return p(DialogueIntent.REPORT_DANGER,DialogueTopic.DANGER,"reported-danger");
        if(any(s,"ik hoorde dat","ik weet dat","ik zag dat","i heard that","i know that","i saw that"))return p(DialogueIntent.PROVIDE_INFORMATION,DialogueTopic.RUMOR,"player-information");
        if(any(s,"kan ik helpen","hulp nodig","wat kan ik doen","can i help","need help","anything i can do"))return p(DialogueIntent.ASK_HELP,DialogueTopic.EVENT,"help");
        if(any(s,"wat vind je van mij","mening over mij","denk je van mij","what do you think of me","opinion of me"))return p(DialogueIntent.ASK_OPINION,DialogueTopic.PLAYER,"player");
        if(any(s,"wie vertelde","van wie hoorde","wat is je bron","who told","source","where did you hear"))return p(DialogueIntent.ASK_SOURCE,context.lastTopic(),context.lastSubject());
        if(any(s,"waar gingen ze","waar zijn ze","waarheen gingen","where did they","where are they","which way did they"))return p(DialogueIntent.ASK_DIRECTION,context.lastTopic()==DialogueTopic.NONE?DialogueTopic.LOCATION:context.lastTopic(),context.lastSubject());

        if(any(s,"hoe oud ben je","wat is je leeftijd","how old are you","your age"))return p(DialogueIntent.ASK_AGE,DialogueTopic.AGE,"age");
        if(any(s,"wie ben je","hoe heet je","jouw naam","vertel over jezelf","who are you","your name","tell me about yourself"))return p(DialogueIntent.ASK_SELF,DialogueTopic.SELF,"self");
        if(any(s,"wat doe je","beroep","werk je","jouw werk","your job","what do you do","occupation","profession"))return p(DialogueIntent.ASK_JOB,DialogueTopic.JOB,"job");
        if(any(s,"familie","gezin","partner","kinderen","ouders","broer","zus","family","husband","wife","partner","children","parents","sibling"))return p(DialogueIntent.ASK_FAMILY,DialogueTopic.FAMILY,"family");
        if(any(s,"hoe gaat het met je","gezondheid","ziek","ziekte","dokter","genezer","health","are you ill","disease","sick","healer"))return p(DialogueIntent.ASK_HEALTH,DialogueTopic.HEALTH,"health");

        if(any(s,"ben ik gezocht","ben ik wanted","staat er een premie op mij","am i wanted","bounty on me"))return p(DialogueIntent.ASK_CRIME,DialogueTopic.CRIME,"wanted");
        if(any(s,"misdaad hier","criminaliteit","zijn er criminelen","crime here","crime rate","criminals here"))return p(DialogueIntent.ASK_CRIME,DialogueTopic.CRIME,"crime");
        if(any(s,"belasting","belastingen","tax","taxes","tribute","tribut"))return p(DialogueIntent.ASK_TAX,DialogueTopic.TAX,"tax");
        if(any(s,"wet","wetten","straf","gevangenis","rechtbank","misdaad","law","laws","punishment","prison","court","crime"))return p(DialogueIntent.ASK_LAW,DialogueTopic.LAW,"law");
        if(any(s,"erfgenaam","opvolger","dynastie","koningshuis","regent","wie volgt de koning","heir","successor","dynasty","royal house","regent"))return p(DialogueIntent.ASK_DYNASTY,DialogueTopic.DYNASTY,"dynasty");
        if(any(s,"politiek","bestuur","regering","democr","tirann","theocr","politics","government","rule here"))return p(DialogueIntent.ASK_POLITICS,DialogueTopic.POLITICS,"politics");
        if(any(s,"koning","koningin","heerser","leider","king","queen","ruler","mayor"))return p(DialogueIntent.ASK_RULER,DialogueTopic.RULER,"ruler");
        if(any(s,"welk rijk","welk koninkrijk","welke factie","jouw rijk","kingdom","realm","faction","which kingdom"))return p(DialogueIntent.ASK_FACTION,DialogueTopic.FACTION,"faction");
        if(any(s,"dit dorp","deze stad","waar woon je","hoe is het hier","de nederzetting","this village","this town","this city","where do you live","settlement"))return p(DialogueIntent.ASK_SETTLEMENT,DialogueTopic.SETTLEMENT,"settlement");

        if(any(s,"hoe sterk is het leger","hoe groot is het leger","legersterkte","army strength","how big is the army","how strong is the army"))return p(DialogueIntent.ASK_ARMY,DialogueTopic.ARMY,"army");
        if(any(s,"wachters","guards","guard patrol","patrouille"))return p(DialogueIntent.ASK_GUARDS,DialogueTopic.GUARDS,"guards");
        if(any(s,"oorlog","leger","soldaten","vijand","beleger","war","army","soldiers","enemy","siege"))return p(DialogueIntent.ASK_WAR,DialogueTopic.WAR,"war");
        if(any(s,"vluchteling","migratie","migreren","vertrekken mensen","refugee","migration","people leaving","people arriving"))return p(DialogueIntent.ASK_MIGRATION,DialogueTopic.MIGRATION,"migration");
        if(any(s,"cultuur","traditie","gewoonte","dialect","taal hier","culture","tradition","custom","dialect","language here"))return p(DialogueIntent.ASK_CULTURE,DialogueTopic.CULTURE,"culture");
        if(any(s,"religie","geloof","god","tempel","priester","religion","faith","temple","priest","worship"))return p(DialogueIntent.ASK_RELIGION,DialogueTopic.RELIGION,"religion");
        if(any(s,"geschiedenis","vroeger","legende","held","monument","history","legend","hero","monument","long ago"))return p(DialogueIntent.ASK_HISTORY,DialogueTopic.HISTORY,"history");
        if(any(s,"gerucht","roddel","heb je iets gehoord","rumor","rumour","gossip","heard anything"))return p(DialogueIntent.ASK_RUMOR,DialogueTopic.RUMOR,"rumor");

        if(any(s,"schoon water","drinkwater","watertekort","waar is de put","water supply","clean water","water shortage","where is the well"))return p(DialogueIntent.ASK_WATER,DialogueTopic.WATER,"water");
        if(any(s,"wat kost","hoe duur","prijs van","price of","how much is"))return p(DialogueIntent.ASK_PRICE,DialogueTopic.PRICE,resourceSubject(s));
        if(any(s,"grondstof","grondstoffen","hout","ijzer","mijn","waterbron","resources","resource","wood","iron","mine","water source"))return p(DialogueIntent.ASK_RESOURCES,DialogueTopic.RESOURCES,"resources");
        if(any(s,"school","leraar","onderwijs","opleiding","school here","teacher","education here"))return p(DialogueIntent.ASK_SCHOOL,DialogueTopic.SCHOOL,"school");
        if(any(s,"technologie","kennis","uitvinding","technology","knowledge","invention"))return p(DialogueIntent.ASK_TECHNOLOGY,DialogueTopic.TECHNOLOGY,"technology");
        if(any(s,"hoe gaat de handel","markt hier","prijzen hier","economie","trade here","market here","prices","economy"))return p(DialogueIntent.ASK_TRADE,DialogueTopic.TRADE,"market");
        if(any(s,"ik wil handelen","wil kopen","wil verkopen","handel met mij","open handel","trade with me","i want to buy","i want to sell","open trade"))return p(DialogueIntent.TRADE,DialogueTopic.TRADE,"market");
        if(any(s,"eten kopen","voedsel kopen","waar kan ik eten","food","buy food","where can i eat"))return p(DialogueIntent.ASK_FOOD,DialogueTopic.FOOD,"food");

        if(any(s,"welk seizoen","welke dag","welk jaar","wat is de datum","season is it","what day is it","what year is it","date today"))return p(DialogueIntent.ASK_CALENDAR,DialogueTopic.CALENDAR,"calendar");
        if(any(s,"welke route","welke weg","weg naar","handelsroute","route to","road to","trade route"))return p(DialogueIntent.ASK_ROUTE,DialogueTopic.ROUTE,"route");
        if(any(s,"gisteren","vandaag","recent","wat is er gebeurd","nieuws","yesterday","today","recently","what happened","news"))return p(DialogueIntent.ASK_RECENT_EVENT,DialogueTopic.EVENT,"recent");
        if(any(s,"bandiet","rovers","raiders","bandit","brigand"))return p(DialogueIntent.ASK_DANGER,DialogueTopic.BANDITS,"bandits");
        if(any(s,"gevaar","veilig","aanval","danger","safe","attack","threat nearby"))return p(DialogueIntent.ASK_DANGER,DialogueTopic.DANGER,"danger");
        String where=afterAny(s,"waar is ","waar ligt ","waar vind ik ","where is ","where can i find ");if(!where.isBlank())return p(DialogueIntent.ASK_DIRECTION,DialogueTopic.LOCATION,where);
        if(any(s,"hallo","hoi","hey","hello","greetings","goedendag")||tokens.size()<=2&&tokens.contains("hi"))return p(DialogueIntent.GREET,DialogueTopic.NONE,"");
        return p(DialogueIntent.UNKNOWN,DialogueTopic.NONE,"");
    }

    private static String answerAge(SocialCitizen c,long day){int age=c.ageYears(day);return compose(c,day,"age",List.of("I am "+age+" years old","I've seen "+age+" years","I am "+age+" now"))+".";}
    private static String answerDynasty(SimulationState state,SocialCitizen c,Faction f,long day){
        DynastyState dynasty=state.dynasties().get(f.id());if(dynasty==null)return compose(c,day,"dynasty_none",List.of("There is no established ruling house I can name","Our government is not recorded as a hereditary house","I don't know of a recognized dynasty here"))+".";
        if(!authority(c)&&c.role()!=CitizenRole.SCHOLAR&&c.role()!=CitizenRole.PRIEST)return "The ruling house is House "+dynasty.houseName()+", and "+f.rulerName()+" rules us.";
        String heir=dynasty.heirCitizenId()>0?state.findSocialCitizen(dynasty.heirCitizenId()).map(SocialCitizen::name).orElse("an unnamed heir"):"no confirmed heir";
        String regency=dynasty.regency()?state.findSocialCitizen(dynasty.regentCitizenId()).map(x->" A regency is being held by "+x.name()+".").orElse(" A regency is currently in force."):"";
        String crisis=dynasty.successionCrisis()?" The succession is disputed.":"";
        return "House "+dynasty.houseName()+" is in generation "+dynasty.generation()+". The recognized succession currently has "+heir+"."+regency+crisis;
    }
    private static String answerCrime(SimulationState state,SocialCitizen c,Settlement s,Faction f,String playerKey,String subject,long day){
        if("wanted".equals(subject)){var wanted=state.crimeLedger().findProfile(playerKey).flatMap(p->p.find(f.id()));if(wanted.isEmpty()||wanted.get().wantedLevel().name().equals("NONE"))return "As far as this realm's records show, the guards are not currently looking for you.";var w=wanted.get();return "Here, your status is "+pretty(w.wantedLevel().name())+" with a bounty of about "+Math.round(w.bounty())+" and heat "+Math.round(w.heat())+".";}
        long active=state.justiceCases().stream().filter(JusticeCase::active).filter(j->j.settlementId()==s.id()).count();if(authority(c))return "There "+(active==1?"is":"are")+" "+active+" active local court "+(active==1?"case":"cases")+". Public order is "+level(s.publicOrder())+" and enforcement is "+level(f.government().lawEnforcement())+".";return s.publicOrder()<.42?"People are worried about crime here. The guards have more work than they can comfortably handle.":compose(c,day,"crime",List.of("Crime happens, but the guards usually keep order","I would not call this place lawless","Most people here still trust the streets well enough"))+".";
    }
    private static String answerWater(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day){SettlementCivilizationState civ=state.ensureSettlementCivilization(s.id(),f.id());boolean well=has(s,"well:"),irrigation=has(s,"irrigation:"),aqueduct=has(s,"aqueduct:");String infrastructure=(aqueduct?"an aqueduct":well?"a public well":irrigation?"irrigation works":"no major dedicated waterworks");return compose(c,day,"water",List.of("Water security is "+level(civ.waterSecurity()),"Our access to clean water is "+level(civ.waterSecurity())))+". We have "+infrastructure+", and sanitation is "+level(civ.sanitation())+".";}
    private static String answerArmy(SimulationState state,SocialCitizen c,Faction f,long day){int personnel=f.armies().stream().mapToInt(Army::totalPersonnel).sum();double morale=f.armies().stream().mapToDouble(Army::morale).average().orElse(.5);if(!authority(c)&&c.role()!=CitizenRole.SCHOLAR)return personnel<=0?"I don't know of a standing field army here.":compose(c,day,"army_common",List.of("We have soldiers in the realm, but I don't know the exact strength","The realm keeps armed forces, though troop numbers are not something people like me are told"))+".";return "The realm currently has about "+personnel+" represented personnel across "+f.armies().size()+" field formations. Their average morale is "+level(morale)+".";}
    private static String answerGuards(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day){long named=state.socialCitizens().stream().filter(SocialCitizen::alive).filter(x->x.settlementId()==s.id()&&x.role()==CitizenRole.GUARD).count();boolean barracks=has(s,"barracks:");String presence=level(Math.min(1,.25+f.government().lawEnforcement()*.55+(barracks?.15:0)));if(authority(c))return "Guard presence here is "+presence+". We currently track "+named+" named guard representatives"+(barracks?" and have barracks support.":".");return compose(c,day,"guards",List.of("The guard presence feels "+presence,"Patrol coverage here is "+presence))+".";}
    private static String answerRoute(SimulationState state,SocialCitizen c,Settlement s,long day,List<DialogueAction> actions){List<TransportRoute> routes=state.routes().stream().filter(TransportRoute::operational).filter(r->r.fromSettlementId()==s.id()||r.toSettlementId()==s.id()).sorted(Comparator.comparingDouble(TransportRoute::quality).reversed()).toList();if(routes.isEmpty())return "I don't know of an established operational route leaving this settlement.";TransportRoute r=routes.getFirst();long otherId=r.fromSettlementId()==s.id()?r.toSettlementId():r.fromSettlementId();Settlement other=state.findSettlement(otherId).orElse(null);if(other==null)return "There is a route from here, but I cannot give you a reliable destination.";if(c.role()!=CitizenRole.TRADER&&!authority(c)&&c.role()!=CitizenRole.SAILOR&&c.role()!=CitizenRole.DOCKWORKER&&c.role()!=CitizenRole.SCHOLAR)return "There is a recognized road or route toward "+other.name()+", but a trader, scholar or guard would know its condition better.";double precision=CartographicKnowledgeEngine.localPrecision(state,c.factionId(),other.position());actions.add(new DialogueAction(DialogueActionType.MARK_LOCATION,"settlement:"+other.id(),other.position(),Math.min(r.security(),precision)));String mapNote=precision<.45?" Our maps of the far end are rough.":precision>.78?" Our maps of that route are considered reliable.":"";return "The "+pretty(r.mode().name())+" route to "+other.name()+" is about "+Math.round(r.distanceBlocks())+" blocks long. Its security is "+level(r.security())+" and quality is "+level(r.quality())+"."+mapNote;}
    private static String answerPrice(SocialCitizen c,Faction f,Settlement s,String subject,long day){ResourceType resource=parseResource(subject);if(resource==null)return compose(c,day,"price_unknown",List.of("Tell me which good you mean","Name the resource and I can tell you the market rate","Which price are you asking about"))+".";var quote=LocalMarketEngine.quote(f,s,resource,day);String certainty=c.role()==CitizenRole.TRADER||c.role()==CitizenRole.OFFICIAL?"":"Roughly, ";int weekday=Math.floorMod((int)day,7);String marketNote=(weekday==0||weekday==3)?" Market day is pushing prices a little.":(weekday==6?" It's the quiet day, so stalls are thinner.":"");return certainty+pretty(resource.name())+" is trading around "+String.format(Locale.ROOT,"%.2f",quote.unitPrice())+" per unit here in "+s.name()+". Local supply is "+(quote.supplyDays()<2?"very tight":quote.supplyDays()<6?"limited":"comfortable")+"."+marketNote;}
    private static String answerSchool(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day){SettlementCivilizationState civ=state.ensureSettlementCivilization(s.id(),f.id());boolean school=has(s,"school:");long teachers=state.socialCitizens().stream().filter(SocialCitizen::alive).filter(x->x.settlementId()==s.id()&&(x.role()==CitizenRole.TEACHER||x.role()==CitizenRole.SCHOLAR)).count();if(school)return "There is a school here. Education is "+level(civ.education())+", with "+teachers+" named teacher or scholar representatives passing on knowledge.";return compose(c,day,"school_none",List.of("There is no proper school here yet","Education here is mostly passed through families and apprenticeships","We do not have a dedicated school building"))+". Local education is "+level(civ.education())+".";}
    private static String answerCalendar(SocialCitizen c,long day){return compose(c,day,"calendar",List.of("By our calendar it is ","The date is "))+CivilizationCalendar.dateLabel(day)+".";}
    private static String reportInformation(SimulationState state,SocialCitizen c,String playerKey,MemoryType type,String subject,String summary,double confidence,List<DialogueAction> actions,boolean alert){Settlement s=state.findSettlement(c.settlementId()).orElseThrow();c.remember(new CitizenMemory(state.clock().day(),type,subject,playerKey,summary,s.position(),.42,confidence));if(alert)actions.add(new DialogueAction(DialogueActionType.NOTIFY_GUARDS,subject,s.position(),confidence));return alert?"I will pass that report to the local guards. They will treat it as a report, not proven fact.":"I'll remember that you told me. Until someone confirms it, I will treat it as information from you rather than established fact.";}
    private static String answerSelf(SocialCitizen c,Settlement s,Faction f,long day){return compose(c,day,"self",List.of("I'm "+c.name()+", a "+roleName(c.role())+" from "+s.name()+".","My name is "+c.name()+". I serve as "+article(roleName(c.role()))+" "+roleName(c.role())+" in "+f.name()+".","People call me "+c.name()+". I live here in "+s.name()+"."));}
    private static String answerJob(SocialCitizen c,Settlement s,long day){String work=switch(c.role()){case FARMER->"I work the fields and help keep the settlement fed.";case MINER->"I work the mines and bring stone and ore into the settlement.";case LUMBERJACK->"I cut timber for homes, workshops and roads.";case HUNTER->"I hunt for food and keep an eye on dangerous wildlife.";case FISHER->"I fish the local waters for food.";case ARTISAN->"I turn raw materials into useful goods.";case TRADER->"I buy, sell and follow the roads where goods are needed.";case BUILDER->"I build and repair the settlement as it grows.";case GUARD->"I patrol, keep order and answer threats.";case OFFICIAL->"I deal with administration, law and the affairs of the realm.";case HEALER->"I treat injuries and sickness when I can.";case PRIEST->"I tend to faith, rites and the community.";case SCHOLAR->"I study and preserve knowledge.";case BUTCHER->"I process livestock and game into food for the settlement.";case CARPENTER->"I turn timber into buildings, furniture and repairs.";case TEACHER->"I teach younger people and pass on useful knowledge.";case SAILOR->"I work the waterways, moving people and goods by boat.";case DOCKWORKER->"I load cargo and keep the docks moving.";case SPY->"I do discreet work for people who prefer not to be named.";};String experience=GuildRank.guildedRole(c.role())?" In the craft I am a "+GuildRank.of(c).titleFor(c.role())+".":c.professionSkill()>.78?" I am considered highly skilled at it.":c.professionSkill()>.48?" I know the trade well.":c.professionSkill()<.25?" I am still learning the trade.":"";return compose(c,day,"job",List.of(work+experience,"My work? "+work+experience,"Around "+s.name()+", "+work.toLowerCase(Locale.ROOT)+experience));}
    private static String answerFamily(SimulationState state,SocialCitizen c,long day){List<String> family=new ArrayList<>();for(CitizenRelationship r:c.relationships().values())if(r.familyBond()!=FamilyBond.NONE){long id=parseCitizenKey(r.targetKey());String name=id>0?state.findSocialCitizen(id).map(SocialCitizen::name).orElse(r.targetKey()):r.targetKey();family.add(familyLabel(r.familyBond())+" "+name);}if(family.isEmpty())return compose(c,day,"family_none",List.of("I don't have close family here that I talk about.","No close household ties that matter here right now.","I mostly keep to myself when it comes to family."));return "My family here includes "+String.join(", ",family.subList(0,Math.min(4,family.size())))+".";}
    private static String answerHealth(SimulationState state,SocialCitizen c,Settlement s,long day){Faction owner=state.findSettlementOwner(s.id()).orElseThrow();SettlementCivilizationState civ=state.ensureSettlementCivilization(s.id(),owner.id());String personal=c.health()>.75?"I feel well enough":c.health()>.45?"I've been better":"I'm not well";String local=civ.diseasePressure()>.65?"There is serious sickness going around.":civ.diseasePressure()>.35?"There has been some sickness lately.":"There is no major outbreak that I know of.";return compose(c,day,"health",List.of(personal+". "+local,local+" As for me, "+personal.toLowerCase(Locale.ROOT)+"."));}
    private static String answerRuler(SocialCitizen c,Faction f,long day){String relation=c.role()==CitizenRole.OFFICIAL||c.role()==CitizenRole.GUARD?"I serve under ":"Our ruler is ";return compose(c,day,"ruler",List.of(relation,"The realm is ruled by "))+f.rulerName()+" of "+f.name()+".";}
    private static String answerSettlement(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day){SettlementCivilizationState civ=state.ensureSettlementCivilization(s.id(),f.id());String size=s.tier().name().toLowerCase(Locale.ROOT);String mood=s.unrest()>.55?"People are angry and tense":s.prosperity()>.68?"Business is good and the place is growing":"Life is fairly ordinary";String detail=(c.role()==CitizenRole.OFFICIAL||c.role()==CitizenRole.TRADER||c.role()==CitizenRole.SCHOLAR)?" We have roughly "+roundPopulation(s.population())+" people, and water security is "+level(civ.waterSecurity())+".":"";String why=" "+WorldCauseExplainer.settlementPressureCause(state,f,s);return compose(c,day,"settlement",List.of("This is "+s.name()+", a "+size+" of "+f.name()+". "+mood+".","You're in "+s.name()+". "+mood+"."))+detail+why;}
    private static String answerFaction(SimulationState state,SocialCitizen c,Faction f,long day){FactionCivilizationState civ=state.ensureFactionCivilization(f.id());String extra=authority(c)?" Government: "+pretty(f.government().type().name())+"; stability is "+level(f.government().stability())+".":"";return compose(c,day,"faction",List.of("We belong to "+f.name()+", ruled by "+f.rulerName()+".","This land is part of "+f.name()+". Our people call our culture "+civ.cultureName()+"."))+extra;}
    private static String answerPolitics(SimulationState state,SocialCitizen c,Faction f,long day){if(!authority(c)&&c.role()!=CitizenRole.SCHOLAR)return compose(c,day,"politics_common",List.of("I leave court politics to people with cleaner clothes than mine","I know who rules us, but not every bargain made at court","Ask an official if you want the details of government"))+". "+f.rulerName()+" rules "+f.name()+".";FactionCivilizationState civ=state.ensureFactionCivilization(f.id());return "The government is "+pretty(f.government().type().name())+" under "+f.rulerName()+". Stability is "+level(f.government().stability())+", legitimacy "+level(f.government().legitimacy())+", and public propaganda pressure "+level(civ.propaganda())+".";}
    private static String answerLaw(SocialCitizen c,Settlement s,Faction f,long day){boolean court=has(s,"courthouse:"),prison=has(s,"prison:");if(authority(c))return "Law enforcement here is "+level(f.government().lawEnforcement())+". "+(court?"There is a court here. ":"")+(prison?"Serious offenders can be imprisoned.":"Serious cases are handled by the realm's authorities.");return compose(c,day,"law",List.of("Stealing, assault and murder will bring the guards down on you","Keep your hands off what isn't yours and you should have little trouble","The guards enforce the local law; serious crimes can follow you through the realm"))+".";}
    private static String answerTax(SocialCitizen c,Faction f,long day){double tax=f.government().taxRate();if(authority(c)||c.role()==CitizenRole.TRADER)return "The current realm tax rate is about "+Math.round(tax*100)+" percent. People would call that "+(tax>.30?"heavy":tax>.18?"noticeable":"fairly light")+".";return compose(c,day,"tax",List.of(tax>.30?"Taxes feel heavy right now":tax>.18?"The tax collectors take a noticeable share":"Taxes are not especially harsh at the moment","Ask an official for the exact rate"))+".";}
    private static String answerFood(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day,List<DialogueAction> actions){actions.add(new DialogueAction(DialogueActionType.MARK_LOCATION,"market:"+s.id(),s.position(),0));double localFood=s.stockpile().get(ResourceType.FOOD);String why=WorldCauseExplainer.settlementPressureCause(state,f,s);if(s.foodSecurity()<.35||localFood<s.population()*.8)return compose(c,day,"food_low",List.of("Food is scarce","We're short on food","The stores are running thin"))+". "+why+" Try the market in "+s.name()+", but expect high prices.";return compose(c,day,"food",List.of("Try the market","You should find food at the market","The traders usually have provisions"))+" here in "+s.name()+". The granary looks "+stockLevel(localFood)+". "+why;}
    private static String answerResources(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day){List<ResourceClaim> claims=state.resourceClaims().stream().filter(ResourceClaim::active).filter(x->x.settlementId()==s.id()).toList();if(claims.isEmpty())return "I don't know of any important claimed resources around here.";String types=claims.stream().map(x->pretty(x.type().name())).distinct().limit(5).reduce((a,b)->a+", "+b).orElse("resources");boolean contested=claims.stream().anyMatch(x->x.contestedByFactionId()>0);String stock="";if(c.role()==CitizenRole.MINER||c.role()==CitizenRole.TRADER||c.role()==CitizenRole.OFFICIAL)stock=" Local iron is "+stockLevel(s.stockpile().get(ResourceType.IRON)+f.stockpile().get(ResourceType.IRON))+" and the granary is "+stockLevel(s.stockpile().get(ResourceType.FOOD))+".";return "This settlement claims access to "+types+"."+(contested?" Some of those claims are disputed.":"")+stock;}
    private static String answerTradeState(SocialCitizen c,Settlement s,Faction f,long day){String state=s.prosperity()>.7?"Trade is lively":s.prosperity()<.35?"Trade is struggling":"Trade is steady";var foodQuote=LocalMarketEngine.quote(f,s,ResourceType.FOOD,day);String detail=c.role()==CitizenRole.TRADER||c.role()==CitizenRole.OFFICIAL?". Food stock is "+stockLevel(s.stockpile().get(ResourceType.FOOD))+" at about "+String.format(Locale.ROOT,"%.2f",foodQuote.unitPrice())+" a unit, and tools are "+stockLevel(s.stockpile().get(ResourceType.TOOLS)+f.stockpile().get(ResourceType.TOOLS)):"";return compose(c,day,"trade_state",List.of(state+" in "+s.name(),"The market here is "+(s.prosperity()>.65?"busy":"functioning")))+detail+".";}
    private static String answerTechnology(SimulationState state,SocialCitizen c,Faction f,long day){FactionCivilizationState civ=state.ensureFactionCivilization(f.id());if(c.role()!=CitizenRole.SCHOLAR&&c.role()!=CitizenRole.ARTISAN&&c.role()!=CitizenRole.OFFICIAL)return compose(c,day,"tech_common",List.of("Scholars and craftspeople know more about that than I do","New techniques spread when traders, schools and workers carry them between towns","I only know the methods used in my own work"))+".";return "Our technical development is "+level(Math.min(1,f.technology()))+" and education is "+level(civ.education())+". Schools, scholars, craftspeople and trade help knowledge spread.";}
    private static String answerWar(SimulationState state,SocialCitizen c,Faction f,long day,List<DialogueAction> actions){List<dev.livingrealms.sim.diplomacy.WarState> wars=state.wars().stream().filter(w->w.active()&&(w.attackerFactionId()==f.id()||w.defenderFactionId()==f.id())).toList();if(wars.isEmpty())return compose(c,day,"peace",List.of("Our realm is not in an open war right now","There is no declared war involving us at the moment","For now, there is no open war for our realm"))+".";var war=wars.getFirst();long enemyId=war.attackerFactionId()==f.id()?war.defenderFactionId():war.attackerFactionId();String enemy=state.findFaction(enemyId).map(Faction::name).orElse("another realm");if(authority(c)||c.role()==CitizenRole.TRADER){if(war.targetSettlementId()>0)state.findSettlement(war.targetSettlementId()).ifPresent(s->actions.add(new DialogueAction(DialogueActionType.MARK_LOCATION,"war_target:"+s.id(),s.position(),0)));return "We are at war with "+enemy+". War exhaustion is "+level(war.attackerFactionId()==f.id()?war.attackerExhaustion():war.defenderExhaustion())+" and the fighting has lasted "+Math.max(0,day-war.startDay())+" days.";}return "Yes. We're at war with "+enemy+". I know what reaches the streets, not every military plan.";}
    private static String answerMigration(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day){SettlementCivilizationState civ=state.ensureSettlementCivilization(s.id(),f.id());String local=civ.refugeePressure()>.62?"Many people are thinking of leaving or seeking safety elsewhere":civ.refugeePressure()>.32?"Some families have been moving because of local pressure":"There is no large movement of people here right now";if(c.role()==CitizenRole.OFFICIAL||c.role()==CitizenRole.TRADER)return local+". Refugee pressure is "+level(civ.refugeePressure())+"; food, safety, disease and war all affect where people go.";return local+".";}
    private static String answerCulture(SimulationState state,SocialCitizen c,Faction f,long day){FactionCivilizationState civ=state.ensureFactionCivilization(f.id());return compose(c,day,"culture",List.of("Our culture is known as "+civ.cultureName(),"Around here people follow "+civ.cultureName()+" customs"))+". You'll hear "+civ.dialectName()+" in everyday speech. Cultural cohesion is "+level(civ.culturalInfluence())+".";}
    private static String answerReligion(SimulationState state,SocialCitizen c,Faction f,long day){
        FactionCivilizationState civ=state.ensureFactionCivilization(f.id());
        FaithCatalog.FaithProfile faith=FaithCatalog.of(civ.faithName());
        String calendar=faith.isHolyDay(day)?" Today is a holy day of "+faith.primaryDeity()+".":faith.isFastingDay(day)?" Today is a fasting day under "+faith.name()+".":"";
        if(c.role()==CitizenRole.PRIEST)
            return "I serve "+faith.name()+", whose primary devotion is "+faith.primaryDeity()+". Our teaching: "+faith.dogma()+". The "+faith.scripture()+" and the mark of the "+faith.symbol()+" guide us. The "+faith.holyOrder()+" keep the vows. Religious influence here is "+level(civ.religiousInfluence())+"."+calendar;
        return "The dominant faith of "+f.name()+" is "+faith.name()+" (honoring "+faith.primaryDeity()+"). Priests speak of the "+faith.scripture()+"; temples show the "+faith.symbol()+"."+calendar;
    }
    private static String answerHistory(SimulationState state,SocialCitizen c,Faction f,Settlement s,long day){List<LegendRecord> local=state.legends().stream().filter(l->l.factionId()==f.id()&&(l.settlementId()==0||l.settlementId()==s.id())).sorted(Comparator.comparingLong(LegendRecord::day).reversed()).toList();if(!local.isEmpty()&&(c.role()==CitizenRole.SCHOLAR||c.role()==CitizenRole.PRIEST||c.role()==CitizenRole.OFFICIAL)){LegendRecord l=local.getFirst();return "One remembered story is '"+l.title()+"'. "+l.description()+(l.monumented()?" There is a monument tied to that memory.":"");}Optional<CitizenMemory> memory=c.latestMemory(m->m.type()==MemoryType.LOCAL_EVENT||m.type()==MemoryType.WAR_NEWS||m.type()==MemoryType.FAMILY_EVENT);return memory.map(value->"What I remember personally is this: "+value.summary()).orElseGet(()->compose(c,day,"history_unknown",List.of("A scholar would know the old stories better than I do","I know local stories, but nothing I would swear is proper history","Ask at a school, temple or official hall if you want recorded history"))+".");}
    private static String answerRumor(SocialCitizen c,long day){Optional<CitizenMemory> rumor=c.latestMemory(m->m.type()==MemoryType.RUMOR||m.type()==MemoryType.WAR_NEWS||m.type()==MemoryType.LOCAL_EVENT);if(rumor.isEmpty())return compose(c,day,"rumor_none",List.of("I haven't heard anything worth repeating","No rumor I trust enough to pass on","Nothing useful has reached me lately"))+".";CitizenMemory m=rumor.get();String uncertainty=m.confidence()<.5?"I wouldn't swear it's true, but ":m.sourceKey().equals("self")?"I saw this myself: ":"I heard that ";return uncertainty+m.summary();}
    private static String answerDanger(SimulationState state,SocialCitizen c,Settlement s,DialogueTopic topic,long day,List<DialogueAction> actions){Optional<CitizenMemory> known=c.latestMemory(m->m.type()==MemoryType.CRIME_WITNESS||m.type()==MemoryType.WAR_NEWS||m.type()==MemoryType.RUMOR||m.type()==MemoryType.LOCAL_EVENT);if(known.isPresent()){CitizenMemory m=known.get();if(m.position()!=null)actions.add(new DialogueAction(DialogueActionType.MARK_LOCATION,m.subjectKey(),m.position(),0));return prefixKnowledge(m)+m.summary();}Faction owner=state.findSettlementOwner(s.id()).orElse(null);SettlementCivilizationState civ=owner==null?null:state.ensureSettlementCivilization(s.id(),owner.id());boolean authority=authority(c);boolean atWar=state.wars().stream().anyMatch(w->w.active()&&(w.attackerFactionId()==c.factionId()||w.defenderFactionId()==c.factionId()));if(authority&&atWar)return compose(c,day,"war",List.of("The realm is at war","There is fighting beyond our roads","The guards are watching for enemy forces"))+". Stay near the roads and gates.";if(civ!=null&&civ.banditPressure()>.55)return "Bandit pressure around this settlement is high. Travel in a group and stay near guarded roads.";if(topic==DialogueTopic.BANDITS)return compose(c,day,"no_bandit",List.of("I haven't seen bandits myself","I haven't heard anything reliable about bandits","No bandits that I can honestly confirm"))+".";return s.publicOrder()<.45?"People here are uneasy. I would avoid traveling alone at night.":"I don't know of any immediate danger nearby.";}
    private static String answerDirection(SimulationState state,SocialCitizen c,DialogueContext context,String parsedSubject,Settlement s,long day,List<DialogueAction> actions){String subject=parsedSubject==null||parsedSubject.isBlank()?context.lastSubject():parsedSubject;Optional<CitizenMemory> memory=c.latestMemory(m->!subject.isBlank()&&(m.subjectKey().toLowerCase(Locale.ROOT).contains(subject.toLowerCase(Locale.ROOT))||m.summary().toLowerCase(Locale.ROOT).contains(subject.toLowerCase(Locale.ROOT))));if(memory.isPresent()){CitizenMemory m=memory.get();actions.add(new DialogueAction(DialogueActionType.MARK_LOCATION,m.subjectKey(),m.position(),0));return "Last I heard, "+direction(s.position(),m.position())+". "+m.summary();}Settlement place=findKnownSettlement(state,c,subject);if(place!=null){actions.add(new DialogueAction(DialogueActionType.MARK_LOCATION,"settlement:"+place.id(),place.position(),0));return place.name()+" is "+directionPhrase(s.position(),place.position())+".";}return compose(c,day,"where_unknown",List.of("I don't know where that is","I couldn't point you there honestly","I don't know enough to give you a direction"))+".";}
    private static String answerSource(SocialCitizen c,DialogueContext context,long day){Optional<CitizenMemory> memory=c.latestMemory(m->!context.lastSubject().isBlank()&&(m.subjectKey().contains(context.lastSubject())||m.summary().toLowerCase(Locale.ROOT).contains(context.lastSubject().toLowerCase(Locale.ROOT))));if(memory.isEmpty())return "I can't give you a source for that.";String source=memory.get().sourceKey();if(source.isBlank()||source.equals("self"))return "I saw or experienced it myself.";return compose(c,day,"source",List.of("I heard it from ","The word came from ","I was told by "))+source+".";}
    private static String answerRecent(SimulationState state,SocialCitizen c,Settlement s,long day){CivicEvent event=state.civicEvents().stream().filter(CivicEvent::active).filter(e->e.settlementId()==s.id()&&e.startDay()<=day&&e.endDay()>=day).max(Comparator.comparingDouble(CivicEvent::intensity).thenComparingLong(CivicEvent::id)).orElse(null);if(event!=null)return "Today people are gathering for "+event.title()+". Attendance is "+level(event.attendance())+" and the event is part of normal life here, not a scripted quest.";Optional<CitizenMemory> m=c.latestMemory(x->x.day()>=Math.max(0,day-7)&&x.type()!=MemoryType.CONVERSATION);if(m.isEmpty())return "Nothing important that I personally know about.";long ago=Math.max(0,day-m.get().day());String when=ago==0?"today":ago==1?"yesterday":ago+" days ago";return "I heard this "+when+": "+m.get().summary();}
    private static String answerOpinion(SocialCitizen c,String playerKey,long day){CitizenRelationship r=c.relationship(playerKey);double score=r.sentiment();if(score>.45)return compose(c,day,"like",List.of("I trust you","You've treated me well","I think well of you"))+".";if(score<-.35)return compose(c,day,"dislike",List.of("I don't trust you","You've given me reason to be wary","I'd rather keep my distance from you"))+".";return compose(c,day,"neutral",List.of("I haven't made up my mind about you","I don't know you well enough yet","You're still a stranger to me"))+".";}
    private static String answerHelp(SimulationState state,SocialCitizen c,Settlement s,Faction f,long day,List<DialogueAction> actions){
        Optional<AssistanceTask> task=state.assistanceTasks().stream().filter(AssistanceTask::active).filter(t->t.settlementId()==s.id()).max(Comparator.comparingDouble(AssistanceTask::remainingPressure));
        if(task.isPresent()){AssistanceTask t=task.get();actions.add(new DialogueAction(DialogueActionType.OFFER_TASK,"task:"+t.id(),s.position(),t.remainingPressure()));
            String deliver=" Deliver verified goods nearby with /livingrealms assist deliver (task #"+t.id()+"); talk alone cannot complete it.";
            return switch(t.type()){
            case MEDICAL_AID -> "There is a real medical shortage here. Cloth and medical supplies would help our healers."+deliver;
            case SECURITY_SUPPORT -> "The roads and homes are under real pressure from bandits or disorder. Iron for the guard and clearing threats would help."+deliver;
            case REFUGEE_SUPPORT -> "Displaced families are arriving faster than we can support them. They need food, safety and shelter."+deliver;
            case FOOD_RELIEF -> "Our food stores are genuinely short. Bring bread or provisions to the settlement."+deliver;
            case WATER_SUPPLY -> "Clean water is our immediate problem. Cloth, sanitation supplies or safer water infrastructure would help."+deliver;
            case HOUSING_SUPPLIES -> "We are short on housing. Builders need timber to put roofs over people."+deliver;
            case TRADE_ESCORT -> "Trade is being hurt by unsafe routes. Iron for escorts or clearing threats along the road would matter."+deliver;
        };}
        SettlementCivilizationState civ=state.ensureSettlementCivilization(s.id(),f.id());String need;double pressure;if(civ.diseasePressure()>.58){need="medical:"+s.id();pressure=civ.diseasePressure();}else if(civ.banditPressure()>.50){need="security:"+s.id();pressure=civ.banditPressure();}else if(civ.refugeePressure()>.50){need="refugees:"+s.id();pressure=civ.refugeePressure();}else{double min=Math.min(c.needs().hunger(),Math.min(c.needs().safety(),c.needs().comfort()));need=(min==c.needs().hunger()?"food":min==c.needs().safety()?"safety":"supplies")+":"+s.id();pressure=1-min;}actions.add(new DialogueAction(DialogueActionType.OFFER_TASK,need,s.position(),pressure));if(need.startsWith("medical"))return "Sickness is putting pressure on people here. Medicine, clean water or help for healers would matter.";if(need.startsWith("security"))return "Banditry and disorder are becoming a problem. The roads and homes need protection.";if(need.startsWith("refugees"))return "Displaced people need food, safety and somewhere to settle.";if(need.startsWith("food"))return "If you want to help, food would matter more than words right now.";if(need.startsWith("safety"))return "The roads and homes need to be safer. Help the guards or deal with nearby threats.";return "Builders and families could use supplies. Ask around the settlement.";
    }
    private static String interaction(SimulationState state,SocialCitizen c,String playerKey,MemoryType type,double friendship,double hostility,double reputation,String response,List<DialogueAction> actions){CitizenRelationship rel=c.relationship(playerKey);rel.adjust(friendship,hostility,0,hostility*.35,friendship-hostility*.5);c.remember(new CitizenMemory(state.clock().day(),type,playerKey,playerKey,response,state.findSettlement(c.settlementId()).orElseThrow().position(),Math.min(1,Math.abs(friendship)+Math.abs(hostility)+.25),1));double value=state.playerStanding(playerKey).adjustReputation(c.factionId(),reputation);actions.add(new DialogueAction(DialogueActionType.REPUTATION_CHANGED,"faction:"+c.factionId(),null,value));if(type==MemoryType.THREAT&&c.role()==CitizenRole.GUARD)actions.add(new DialogueAction(DialogueActionType.ALERT_GUARDS,playerKey,null,1));return response;}

    private static String unknown(SocialCitizen c,long day){return compose(c,day,"unknown",List.of("I'm not sure what you're asking","I don't know enough about that","I can talk about this place, my work, family, trade, law, war, culture, rumors or danger"))+".";}
    private static String prefixKnowledge(CitizenMemory m){if(m.confidence()<.45)return "I only heard a rumor, but ";if(m.sourceKey().equals("self"))return "I saw it myself: ";return "What I heard is this: ";}
    private static DialogueTopic inferTopic(DialogueIntent intent){return switch(intent){
        case ASK_SELF->DialogueTopic.SELF;case ASK_AGE->DialogueTopic.AGE;case ASK_JOB->DialogueTopic.JOB;case ASK_FAMILY->DialogueTopic.FAMILY;case ASK_HEALTH->DialogueTopic.HEALTH;
        case ASK_RULER->DialogueTopic.RULER;case ASK_DYNASTY->DialogueTopic.DYNASTY;case ASK_SETTLEMENT->DialogueTopic.SETTLEMENT;case ASK_FACTION->DialogueTopic.FACTION;case ASK_POLITICS->DialogueTopic.POLITICS;case ASK_LAW->DialogueTopic.LAW;case ASK_CRIME,REPORT_CRIME->DialogueTopic.CRIME;case ASK_TAX->DialogueTopic.TAX;
        case ASK_FOOD->DialogueTopic.FOOD;case ASK_WATER->DialogueTopic.WATER;case ASK_RESOURCES->DialogueTopic.RESOURCES;case ASK_TRADE,TRADE->DialogueTopic.TRADE;case ASK_PRICE->DialogueTopic.PRICE;case ASK_TECHNOLOGY->DialogueTopic.TECHNOLOGY;case ASK_SCHOOL->DialogueTopic.SCHOOL;
        case ASK_WAR->DialogueTopic.WAR;case ASK_ARMY->DialogueTopic.ARMY;case ASK_GUARDS->DialogueTopic.GUARDS;case ASK_ROUTE->DialogueTopic.ROUTE;case ASK_MIGRATION->DialogueTopic.MIGRATION;case ASK_CULTURE->DialogueTopic.CULTURE;case ASK_RELIGION->DialogueTopic.RELIGION;case ASK_HISTORY->DialogueTopic.HISTORY;case ASK_RUMOR,PROVIDE_INFORMATION->DialogueTopic.RUMOR;case ASK_CALENDAR->DialogueTopic.CALENDAR;
        case ASK_DANGER,REPORT_DANGER->DialogueTopic.DANGER;case ASK_DIRECTION->DialogueTopic.LOCATION;case ASK_RECENT_EVENT,ASK_HELP->DialogueTopic.EVENT;case ASK_OPINION,GIVE_GIFT,COMPLIMENT,APOLOGIZE,THREATEN,INSULT->DialogueTopic.PLAYER;default->DialogueTopic.NONE;};}
    private static String subjectFor(DialogueTopic topic){return switch(topic){case BANDITS->"bandits";case RULER->"ruler";case DYNASTY->"dynasty";case FOOD->"food";case WATER->"water";case TRADE->"market";case PRICE->"price";case PLAYER->"player";case DANGER->"danger";case EVENT->"recent";case LOCATION->"location";case SELF->"self";case AGE->"age";case JOB->"job";case FAMILY->"family";case HEALTH->"health";case SETTLEMENT->"settlement";case FACTION->"faction";case POLITICS->"politics";case LAW->"law";case CRIME->"crime";case TAX->"tax";case RESOURCES->"resources";case TECHNOLOGY->"technology";case SCHOOL->"school";case WAR->"war";case ARMY->"army";case GUARDS->"guards";case ROUTE->"route";case MIGRATION->"migration";case CULTURE->"culture";case RELIGION->"religion";case HISTORY->"history";case RUMOR->"rumor";case CALENDAR->"calendar";default->"";};}
    private static Settlement findKnownSettlement(SimulationState state,SocialCitizen c,String subject){String needle=normalize(subject);if(needle.isBlank()||needle.equals("location"))return null;Settlement home=state.findSettlement(c.settlementId()).orElse(null);for(Faction f:state.factions())for(Settlement s:f.settlements()){String name=normalize(s.name());if(!name.equals(needle)&&!name.contains(needle)&&!needle.contains(name))continue;boolean local=f.id()==c.factionId()||home!=null&&home.position().distanceTo(s.position())<1400||c.role()==CitizenRole.TRADER||authority(c);if(local)return s;}return null;}
    private static boolean authority(SocialCitizen c){return c.role()==CitizenRole.GUARD||c.role()==CitizenRole.OFFICIAL;}
    private static String familyLabel(FamilyBond bond){return switch(bond){case PARENT->"parent";case CHILD->"child";case SIBLING->"sibling";case PARTNER->"partner";case ADOPTIVE_PARENT->"adoptive parent";case ADOPTED_CHILD->"adopted child";case NONE->"relative";};}
    private static String roleName(CitizenRole role){return pretty(role.name());}
    private static String article(String word){if(word==null||word.isEmpty())return "a";return "aeiou".indexOf(Character.toLowerCase(word.charAt(0)))>=0?"an":"a";}
    private static String level(double v){return v>=.8?"very high":v>=.62?"high":v>=.42?"moderate":v>=.22?"low":"very low";}
    private static String stockLevel(double v){return v>=1000?"abundant":v>=250?"healthy":v>=60?"limited":"scarce";}
    private static String roundPopulation(int population){if(population<100)return Integer.toString(population);if(population<1000)return (Math.round(population/25.0)*25)+"";return (Math.round(population/100.0)*100)+"";}
    private static boolean has(Settlement s,String prefix){return s.completedConstruction().stream().anyMatch(k->k.startsWith(prefix));}
    private static String compose(SocialCitizen c,long day,String key,List<String> options){int idx=Math.floorMod(Objects.hash(c.id(),day,key),options.size());return options.get(idx);}
    private static String direction(SimPosition from,SimPosition to){return "they were "+directionPhrase(from,to);}
    private static String directionPhrase(SimPosition from,SimPosition to){double dx=to.x()-from.x(),dz=to.z()-from.z();String ns=dz<-8?"north":dz>8?"south":"";String ew=dx>8?"east":dx<-8?"west":"";String d=(ns+ew).isEmpty()?"nearby":ns+ew;long blocks=Math.round(from.distanceTo(to));return d+" of here, roughly "+blocks+" blocks away";}
    private static boolean any(String s,String...needles){for(String n:needles)if(s.contains(n))return true;return false;}
    private static String afterAny(String s,String...prefixes){for(String p:prefixes){int i=s.indexOf(p);if(i>=0){String x=s.substring(i+p.length()).trim();if(!x.isBlank())return x;}}return "";}
    private static String resourceSubject(String s){ResourceType r=parseResource(s);return r==null?"resource":r.name().toLowerCase(Locale.ROOT);} 
    private static ResourceType parseResource(String s){String n=normalize(s);if(any(n,"eten","voedsel","food","graan","grain"))return ResourceType.FOOD;if(any(n,"hout","wood","timber"))return ResourceType.WOOD;if(any(n,"steen","stone"))return ResourceType.STONE;if(any(n,"ijzer","iron"))return ResourceType.IRON;if(any(n,"kolen","coal"))return ResourceType.COAL;if(any(n,"koper","copper"))return ResourceType.COPPER;if(any(n,"goud","gold"))return ResourceType.GOLD;if(any(n,"brandstof","fuel"))return ResourceType.FUEL;if(any(n,"munitie","ammunition","ammo"))return ResourceType.AMMUNITION;if(any(n,"gereedschap","tools"))return ResourceType.TOOLS;if(any(n,"machines","machinery"))return ResourceType.MACHINERY;if(any(n,"textiel","textiles","cloth"))return ResourceType.TEXTILES;try{return ResourceType.valueOf(n.toUpperCase(Locale.ROOT));}catch(IllegalArgumentException ignored){return null;}}
    private static String normalize(String s){return Normalizer.normalize(Objects.requireNonNullElse(s,"").toLowerCase(Locale.ROOT),Normalizer.Form.NFD).replaceAll("\\p{M}","").replaceAll("[^a-z0-9' ]"," ").replaceAll("\\s+"," ").trim();}
    private static String summarizeInput(String input){String s=input.trim();return s.length()<=160?s:s.substring(0,160);}
    private static String pretty(String value){String x=value.toLowerCase(Locale.ROOT).replace('_',' ');return x.isBlank()?x:Character.toUpperCase(x.charAt(0))+x.substring(1);}
    private static long parseCitizenKey(String key){if(key==null||!key.startsWith("citizen:"))return 0;try{return Long.parseLong(key.substring(8));}catch(NumberFormatException ignored){return 0;}}
    private static Parsed p(DialogueIntent intent,DialogueTopic topic,String subject){return new Parsed(intent,topic,Objects.requireNonNullElse(subject,""));}
    public record Parsed(DialogueIntent intent,DialogueTopic topic,String subject){}
}
