package dev.livingrealms.sim.social;
public enum MemoryType { HELPED_BY, ATTACKED_BY, STOLEN_FROM, GIFT, THREAT, INSULT, TRADE, CONVERSATION, LOCAL_EVENT, RUMOR, WAR_NEWS, CRIME_WITNESS, FAMILY_EVENT, WORK_EVENT }
